/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const ENGINES: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'Brute Force',
    rarity: 'epic',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 8,
        cornering: 6,
        powerUnit: 12,
        reliability: 5,
        pitStopTime: 0.88,
      },
      {
        level: 2,
        speed: 10,
        cornering: 8,
        powerUnit: 15,
        reliability: 7,
        pitStopTime: 0.84,
      },
      {
        level: 3,
        speed: 12,
        cornering: 10,
        powerUnit: 19,
        reliability: 9,
        pitStopTime: 0.81,
      },
      {
        level: 4,
        speed: 14,
        cornering: 12,
        powerUnit: 22,
        reliability: 11,
        pitStopTime: 0.77,
      },
      {
        level: 5,
        speed: 15,
        cornering: 13,
        powerUnit: 26,
        reliability: 12,
        pitStopTime: 0.74,
      },
      {
        level: 6,
        speed: 17,
        cornering: 15,
        powerUnit: 29,
        reliability: 14,
        pitStopTime: 0.7,
      },
      {
        level: 7,
        speed: 19,
        cornering: 17,
        powerUnit: 33,
        reliability: 16,
        pitStopTime: 0.67,
      },
      {
        level: 8,
        speed: 21,
        cornering: 19,
        powerUnit: 36,
        reliability: 18,
        pitStopTime: 0.63,
      },
    ],
  },
  {
    id: 2,
    name: 'Nova',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 11,
        cornering: 3,
        powerUnit: 5,
        reliability: 6,
        pitStopTime: 0.92,
      },
      {
        level: 2,
        speed: 13,
        cornering: 4,
        powerUnit: 6,
        reliability: 7,
        pitStopTime: 0.9,
      },
      {
        level: 3,
        speed: 15,
        cornering: 5,
        powerUnit: 7,
        reliability: 8,
        pitStopTime: 0.88,
      },
      {
        level: 4,
        speed: 17,
        cornering: 6,
        powerUnit: 8,
        reliability: 9,
        pitStopTime: 0.86,
      },
      {
        level: 5,
        speed: 19,
        cornering: 7,
        powerUnit: 9,
        reliability: 10,
        pitStopTime: 0.84,
      },
      {
        level: 6,
        speed: 21,
        cornering: 8,
        powerUnit: 10,
        reliability: 11,
        pitStopTime: 0.82,
      },
      {
        level: 7,
        speed: 23,
        cornering: 9,
        powerUnit: 11,
        reliability: 12,
        pitStopTime: 0.8,
      },
      {
        level: 8,
        speed: 25,
        cornering: 10,
        powerUnit: 12,
        reliability: 13,
        pitStopTime: 0.78,
      },
      {
        level: 9,
        speed: 27,
        cornering: 11,
        powerUnit: 13,
        reliability: 14,
        pitStopTime: 0.76,
      },
      {
        level: 10,
        speed: 29,
        cornering: 12,
        powerUnit: 14,
        reliability: 15,
        pitStopTime: 0.73,
      },
      {
        level: 11,
        speed: 31,
        cornering: 13,
        powerUnit: 15,
        reliability: 16,
        pitStopTime: 0.71,
      },
    ],
  },
  {
    id: 3,
    name: 'Enigma',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 7,
        cornering: 4,
        powerUnit: 9,
        reliability: 11,
        pitStopTime: 0.88,
      },
      {
        level: 2,
        speed: 8,
        cornering: 5,
        powerUnit: 11,
        reliability: 13,
        pitStopTime: 0.86,
      },
      {
        level: 3,
        speed: 9,
        cornering: 6,
        powerUnit: 12,
        reliability: 14,
        pitStopTime: 0.84,
      },
      {
        level: 4,
        speed: 10,
        cornering: 7,
        powerUnit: 14,
        reliability: 16,
        pitStopTime: 0.82,
      },
      {
        level: 5,
        speed: 11,
        cornering: 8,
        powerUnit: 15,
        reliability: 17,
        pitStopTime: 0.8,
      },
      {
        level: 6,
        speed: 12,
        cornering: 9,
        powerUnit: 17,
        reliability: 19,
        pitStopTime: 0.78,
      },
      {
        level: 7,
        speed: 13,
        cornering: 10,
        powerUnit: 18,
        reliability: 20,
        pitStopTime: 0.76,
      },
      {
        level: 8,
        speed: 14,
        cornering: 11,
        powerUnit: 20,
        reliability: 22,
        pitStopTime: 0.73,
      },
      {
        level: 9,
        speed: 15,
        cornering: 12,
        powerUnit: 21,
        reliability: 23,
        pitStopTime: 0.71,
      },
      {
        level: 10,
        speed: 16,
        cornering: 13,
        powerUnit: 23,
        reliability: 25,
        pitStopTime: 0.69,
      },
      {
        level: 11,
        speed: 17,
        cornering: 14,
        powerUnit: 24,
        reliability: 26,
        pitStopTime: 0.67,
      },
    ],
  },
  {
    id: 4,
    name: 'Twinburst',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        speed: 6,
        cornering: 14,
        powerUnit: 8,
        reliability: 7,
        pitStopTime: 0.82,
      },
      {
        level: 2,
        speed: 7,
        cornering: 16,
        powerUnit: 9,
        reliability: 8,
        pitStopTime: 0.79,
      },
      {
        level: 3,
        speed: 8,
        cornering: 17,
        powerUnit: 10,
        reliability: 9,
        pitStopTime: 0.76,
      },
      {
        level: 4,
        speed: 9,
        cornering: 19,
        powerUnit: 11,
        reliability: 10,
        pitStopTime: 0.72,
      },
      {
        level: 5,
        speed: 10,
        cornering: 20,
        powerUnit: 12,
        reliability: 11,
        pitStopTime: 0.69,
      },
      {
        level: 6,
        speed: 11,
        cornering: 22,
        powerUnit: 13,
        reliability: 12,
        pitStopTime: 0.66,
      },
      {
        level: 7,
        speed: 12,
        cornering: 23,
        powerUnit: 14,
        reliability: 13,
        pitStopTime: 0.63,
      },
      {
        level: 8,
        speed: 13,
        cornering: 25,
        powerUnit: 15,
        reliability: 14,
        pitStopTime: 0.6,
      },
      {
        level: 9,
        speed: 14,
        cornering: 26,
        powerUnit: 16,
        reliability: 15,
        pitStopTime: 0.57,
      },
      {
        level: 10,
        speed: 15,
        cornering: 28,
        powerUnit: 17,
        reliability: 16,
        pitStopTime: 0.54,
      },
      {
        level: 11,
        speed: 16,
        cornering: 29,
        powerUnit: 18,
        reliability: 17,
        pitStopTime: 0.51,
      },
    ],
  },
  {
    id: 5,
    name: 'The Rover',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        speed: 14,
        cornering: 11,
        powerUnit: 15,
        reliability: 10,
        pitStopTime: 0.82,
      },
      {
        level: 2,
        speed: 16,
        cornering: 13,
        powerUnit: 17,
        reliability: 12,
        pitStopTime: 0.78,
      },
      {
        level: 3,
        speed: 17,
        cornering: 15,
        powerUnit: 18,
        reliability: 14,
        pitStopTime: 0.75,
      },
      {
        level: 4,
        speed: 19,
        cornering: 16,
        powerUnit: 20,
        reliability: 15,
        pitStopTime: 0.71,
      },
      {
        level: 5,
        speed: 21,
        cornering: 18,
        powerUnit: 22,
        reliability: 17,
        pitStopTime: 0.67,
      },
      {
        level: 6,
        speed: 22,
        cornering: 20,
        powerUnit: 23,
        reliability: 19,
        pitStopTime: 0.64,
      },
      {
        level: 7,
        speed: 24,
        cornering: 22,
        powerUnit: 25,
        reliability: 21,
        pitStopTime: 0.6,
      },
      {
        level: 8,
        speed: 25,
        cornering: 23,
        powerUnit: 26,
        reliability: 22,
        pitStopTime: 0.57,
      },
      {
        level: 9,
        speed: 27,
        cornering: 25,
        powerUnit: 28,
        reliability: 24,
        pitStopTime: 0.53,
      },
    ],
  },
  {
    id: 6,
    name: 'Avalanche',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        speed: 18,
        cornering: 11,
        powerUnit: 13,
        reliability: 9,
        pitStopTime: 0.67,
      },
      {
        level: 2,
        speed: 20,
        cornering: 12,
        powerUnit: 15,
        reliability: 11,
        pitStopTime: 0.63,
      },
      {
        level: 3,
        speed: 22,
        cornering: 14,
        powerUnit: 16,
        reliability: 12,
        pitStopTime: 0.59,
      },
      {
        level: 4,
        speed: 24,
        cornering: 15,
        powerUnit: 18,
        reliability: 14,
        pitStopTime: 0.55,
      },
      {
        level: 5,
        speed: 26,
        cornering: 17,
        powerUnit: 19,
        reliability: 15,
        pitStopTime: 0.51,
      },
      {
        level: 6,
        speed: 28,
        cornering: 18,
        powerUnit: 21,
        reliability: 17,
        pitStopTime: 0.47,
      },
      {
        level: 7,
        speed: 30,
        cornering: 19,
        powerUnit: 22,
        reliability: 18,
        pitStopTime: 0.43,
      },
      {
        level: 8,
        speed: 32,
        cornering: 21,
        powerUnit: 24,
        reliability: 20,
        pitStopTime: 0.39,
      },
      {
        level: 9,
        speed: 34,
        cornering: 22,
        powerUnit: 25,
        reliability: 21,
        pitStopTime: 0.35,
      },
    ],
  },
  {
    id: 7,
    name: 'Cloudroar',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        speed: 13,
        cornering: 12,
        powerUnit: 25,
        reliability: 14,
        pitStopTime: 0.8,
      },
      {
        level: 2,
        speed: 15,
        cornering: 14,
        powerUnit: 29,
        reliability: 16,
        pitStopTime: 0.76,
      },
      {
        level: 3,
        speed: 17,
        cornering: 15,
        powerUnit: 32,
        reliability: 18,
        pitStopTime: 0.73,
      },
      {
        level: 4,
        speed: 19,
        cornering: 17,
        powerUnit: 36,
        reliability: 20,
        pitStopTime: 0.69,
      },
      {
        level: 5,
        speed: 20,
        cornering: 19,
        powerUnit: 39,
        reliability: 21,
        pitStopTime: 0.66,
      },
      {
        level: 6,
        speed: 22,
        cornering: 21,
        powerUnit: 43,
        reliability: 23,
        pitStopTime: 0.62,
      },
      {
        level: 7,
        speed: 24,
        cornering: 22,
        powerUnit: 46,
        reliability: 25,
        pitStopTime: 0.59,
      },
      {
        level: 8,
        speed: 26,
        cornering: 24,
        powerUnit: 50,
        reliability: 27,
        pitStopTime: 0.55,
      },
    ],
  },
] as Part[];

const createEngines = () => {
  const enginesToSave = preparePartData(ENGINES);

  console.log('Creating engines file >>');
  createFile('src/features/parts/constants/engines.json', enginesToSave);
};

export default createEngines;
