/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const FRONT_WINGS: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'The Scout',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 3,
        cornering: 7,
        powerUnit: 5,
        reliability: 4,
        pitStopTime: 0.94,
      },
      {
        level: 2,
        speed: 4,
        cornering: 9,
        powerUnit: 6,
        reliability: 5,
        pitStopTime: 0.92,
      },
      {
        level: 3,
        speed: 5,
        cornering: 11,
        powerUnit: 7,
        reliability: 6,
        pitStopTime: 0.9,
      },
      {
        level: 4,
        speed: 6,
        cornering: 13,
        powerUnit: 8,
        reliability: 7,
        pitStopTime: 0.88,
      },
      {
        level: 5,
        speed: 7,
        cornering: 15,
        powerUnit: 9,
        reliability: 8,
        pitStopTime: 0.86,
      },
      {
        level: 6,
        speed: 8,
        cornering: 17,
        powerUnit: 10,
        reliability: 9,
        pitStopTime: 0.84,
      },
      {
        level: 7,
        speed: 9,
        cornering: 19,
        powerUnit: 11,
        reliability: 10,
        pitStopTime: 0.82,
      },
      {
        level: 8,
        speed: 10,
        cornering: 21,
        powerUnit: 12,
        reliability: 11,
        pitStopTime: 0.8,
      },
      {
        level: 9,
        speed: 11,
        cornering: 23,
        powerUnit: 13,
        reliability: 12,
        pitStopTime: 0.78,
      },
      {
        level: 10,
        speed: 12,
        cornering: 25,
        powerUnit: 14,
        reliability: 13,
        pitStopTime: 0.76,
      },
      {
        level: 11,
        speed: 13,
        cornering: 27,
        powerUnit: 15,
        reliability: 14,
        pitStopTime: 0.73,
      },
    ],
  },
  {
    id: 2,
    name: 'Feral Punch',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 6,
        powerUnit: 8,
        reliability: 7,
        pitStopTime: 0.92,
      },
      {
        level: 2,
        speed: 5,
        cornering: 7,
        powerUnit: 10,
        reliability: 9,
        pitStopTime: 0.9,
      },
      {
        level: 3,
        speed: 6,
        cornering: 8,
        powerUnit: 11,
        reliability: 10,
        pitStopTime: 0.88,
      },
      {
        level: 4,
        speed: 7,
        cornering: 9,
        powerUnit: 13,
        reliability: 12,
        pitStopTime: 0.86,
      },
      {
        level: 5,
        speed: 8,
        cornering: 10,
        powerUnit: 14,
        reliability: 13,
        pitStopTime: 0.84,
      },
      {
        level: 6,
        speed: 9,
        cornering: 11,
        powerUnit: 16,
        reliability: 15,
        pitStopTime: 0.82,
      },
      {
        level: 7,
        speed: 10,
        cornering: 12,
        powerUnit: 17,
        reliability: 16,
        pitStopTime: 0.8,
      },
      {
        level: 8,
        speed: 11,
        cornering: 13,
        powerUnit: 19,
        reliability: 18,
        pitStopTime: 0.78,
      },
      {
        level: 9,
        speed: 12,
        cornering: 14,
        powerUnit: 20,
        reliability: 19,
        pitStopTime: 0.76,
      },
      {
        level: 10,
        speed: 13,
        cornering: 15,
        powerUnit: 22,
        reliability: 21,
        pitStopTime: 0.73,
      },
      {
        level: 11,
        speed: 14,
        cornering: 16,
        powerUnit: 23,
        reliability: 22,
        pitStopTime: 0.71,
      },
    ],
  },
  {
    id: 3,
    name: 'The Vagabond',
    rarity: 'epic',
    series: 3,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 8,
        powerUnit: 11,
        reliability: 9,
        pitStopTime: 0.76,
      },
      {
        level: 2,
        speed: 15,
        cornering: 10,
        powerUnit: 13,
        reliability: 11,
        pitStopTime: 0.7,
      },
      {
        level: 3,
        speed: 17,
        cornering: 11,
        powerUnit: 14,
        reliability: 12,
        pitStopTime: 0.64,
      },
      {
        level: 4,
        speed: 20,
        cornering: 13,
        powerUnit: 16,
        reliability: 14,
        pitStopTime: 0.58,
      },
      {
        level: 5,
        speed: 23,
        cornering: 15,
        powerUnit: 18,
        reliability: 16,
        pitStopTime: 0.52,
      },
      {
        level: 6,
        speed: 26,
        cornering: 17,
        powerUnit: 20,
        reliability: 18,
        pitStopTime: 0.46,
      },
      {
        level: 7,
        speed: 28,
        cornering: 18,
        powerUnit: 21,
        reliability: 19,
        pitStopTime: 0.41,
      },
      {
        level: 8,
        speed: 31,
        cornering: 20,
        powerUnit: 23,
        reliability: 21,
        pitStopTime: 0.35,
      },
    ],
  },
  {
    id: 4,
    name: 'Zeno',
    rarity: 'rare',
    series: 5,
    stats: [
      {
        level: 1,
        speed: 11,
        cornering: 10,
        powerUnit: 9,
        reliability: 12,
        pitStopTime: 0.8,
      },
      {
        level: 2,
        speed: 13,
        cornering: 12,
        powerUnit: 11,
        reliability: 14,
        pitStopTime: 0.76,
      },
      {
        level: 3,
        speed: 15,
        cornering: 13,
        powerUnit: 12,
        reliability: 16,
        pitStopTime: 0.73,
      },
      {
        level: 4,
        speed: 16,
        cornering: 15,
        powerUnit: 14,
        reliability: 17,
        pitStopTime: 0.7,
      },
      {
        level: 5,
        speed: 18,
        cornering: 17,
        powerUnit: 16,
        reliability: 19,
        pitStopTime: 0.66,
      },
      {
        level: 6,
        speed: 20,
        cornering: 18,
        powerUnit: 17,
        reliability: 21,
        pitStopTime: 0.63,
      },
      {
        level: 7,
        speed: 22,
        cornering: 20,
        powerUnit: 19,
        reliability: 23,
        pitStopTime: 0.6,
      },
      {
        level: 8,
        speed: 23,
        cornering: 21,
        powerUnit: 20,
        reliability: 24,
        pitStopTime: 0.56,
      },
      {
        level: 9,
        speed: 25,
        cornering: 23,
        powerUnit: 22,
        reliability: 26,
        pitStopTime: 0.53,
      },
    ],
  },
  {
    id: 5,
    name: 'Trailblazer',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        speed: 10,
        cornering: 11,
        powerUnit: 19,
        reliability: 9,
        pitStopTime: 0.8,
      },
      {
        level: 2,
        speed: 11,
        cornering: 13,
        powerUnit: 22,
        reliability: 10,
        pitStopTime: 0.77,
      },
      {
        level: 3,
        speed: 13,
        cornering: 14,
        powerUnit: 25,
        reliability: 12,
        pitStopTime: 0.74,
      },
      {
        level: 4,
        speed: 14,
        cornering: 16,
        powerUnit: 28,
        reliability: 13,
        pitStopTime: 0.71,
      },
      {
        level: 5,
        speed: 16,
        cornering: 17,
        powerUnit: 31,
        reliability: 15,
        pitStopTime: 0.68,
      },
      {
        level: 6,
        speed: 17,
        cornering: 19,
        powerUnit: 33,
        reliability: 16,
        pitStopTime: 0.66,
      },
      {
        level: 7,
        speed: 18,
        cornering: 20,
        powerUnit: 36,
        reliability: 17,
        pitStopTime: 0.63,
      },
      {
        level: 8,
        speed: 20,
        cornering: 22,
        powerUnit: 39,
        reliability: 19,
        pitStopTime: 0.6,
      },
      {
        level: 9,
        speed: 21,
        cornering: 23,
        powerUnit: 42,
        reliability: 20,
        pitStopTime: 0.57,
      },
    ],
  },
  {
    id: 6,
    name: 'Thunderclap',
    rarity: 'rare',
    series: 10,
    stats: [
      {
        level: 1,
        speed: 18,
        cornering: 12,
        powerUnit: 10,
        reliability: 16,
        pitStopTime: 0.78,
      },
      {
        level: 2,
        speed: 20,
        cornering: 13,
        powerUnit: 11,
        reliability: 18,
        pitStopTime: 0.75,
      },
      {
        level: 3,
        speed: 22,
        cornering: 15,
        powerUnit: 13,
        reliability: 20,
        pitStopTime: 0.72,
      },
      {
        level: 4,
        speed: 24,
        cornering: 16,
        powerUnit: 14,
        reliability: 22,
        pitStopTime: 0.69,
      },
      {
        level: 5,
        speed: 27,
        cornering: 18,
        powerUnit: 16,
        reliability: 25,
        pitStopTime: 0.66,
      },
      {
        level: 6,
        speed: 29,
        cornering: 19,
        powerUnit: 17,
        reliability: 27,
        pitStopTime: 0.64,
      },
      {
        level: 7,
        speed: 31,
        cornering: 20,
        powerUnit: 18,
        reliability: 29,
        pitStopTime: 0.61,
      },
      {
        level: 8,
        speed: 33,
        cornering: 22,
        powerUnit: 20,
        reliability: 31,
        pitStopTime: 0.58,
      },
      {
        level: 9,
        speed: 35,
        cornering: 23,
        powerUnit: 21,
        reliability: 33,
        pitStopTime: 0.55,
      },
    ],
  },
  {
    id: 7,
    name: 'Virtue',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        speed: 11,
        cornering: 25,
        powerUnit: 14,
        reliability: 12,
        pitStopTime: 0.76,
      },
      {
        level: 2,
        speed: 13,
        cornering: 29,
        powerUnit: 16,
        reliability: 14,
        pitStopTime: 0.72,
      },
      {
        level: 3,
        speed: 14,
        cornering: 32,
        powerUnit: 18,
        reliability: 15,
        pitStopTime: 0.68,
      },
      {
        level: 4,
        speed: 16,
        cornering: 36,
        powerUnit: 20,
        reliability: 17,
        pitStopTime: 0.64,
      },
      {
        level: 5,
        speed: 18,
        cornering: 39,
        powerUnit: 21,
        reliability: 19,
        pitStopTime: 0.6,
      },
      {
        level: 6,
        speed: 20,
        cornering: 43,
        powerUnit: 23,
        reliability: 21,
        pitStopTime: 0.57,
      },
      {
        level: 7,
        speed: 21,
        cornering: 46,
        powerUnit: 25,
        reliability: 22,
        pitStopTime: 0.53,
      },
      {
        level: 8,
        speed: 23,
        cornering: 50,
        powerUnit: 27,
        reliability: 24,
        pitStopTime: 0.49,
      },
    ],
  },
] as Part[];

const createFrontWings = () => {
  const frontWingsToSave = preparePartData(FRONT_WINGS);

  console.log('Creating front wings file >>');
  createFile('src/features/parts/constants/frontWings.json', frontWingsToSave);
};

export default createFrontWings;
