/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { preparePartData } from './utils';
import type { Part } from './types';

const GEARBOXES: Part[] = [
  {
    id: 0,
    name: 'Starter',
    rarity: 'stock',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 1,
        cornering: 1,
        powerUnit: 1,
        reliability: 1,
        pitStopTime: 1,
      },
    ],
  },
  {
    id: 1,
    name: 'Switch-R-OO',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        speed: 3,
        cornering: 4,
        powerUnit: 2,
        reliability: 5,
        pitStopTime: 0.84,
      },
      {
        level: 2,
        speed: 4,
        cornering: 5,
        powerUnit: 3,
        reliability: 6,
        pitStopTime: 0.8,
      },
      {
        level: 3,
        speed: 5,
        cornering: 6,
        powerUnit: 4,
        reliability: 7,
        pitStopTime: 0.76,
      },
      {
        level: 4,
        speed: 6,
        cornering: 7,
        powerUnit: 5,
        reliability: 8,
        pitStopTime: 0.71,
      },
      {
        level: 5,
        speed: 7,
        cornering: 8,
        powerUnit: 6,
        reliability: 9,
        pitStopTime: 0.67,
      },
      {
        level: 6,
        speed: 8,
        cornering: 9,
        powerUnit: 7,
        reliability: 10,
        pitStopTime: 0.63,
      },
      {
        level: 7,
        speed: 9,
        cornering: 10,
        powerUnit: 8,
        reliability: 11,
        pitStopTime: 0.59,
      },
      {
        level: 8,
        speed: 10,
        cornering: 11,
        powerUnit: 9,
        reliability: 12,
        pitStopTime: 0.55,
      },
      {
        level: 9,
        speed: 11,
        cornering: 12,
        powerUnit: 10,
        reliability: 13,
        pitStopTime: 0.51,
      },
      {
        level: 10,
        speed: 12,
        cornering: 13,
        powerUnit: 11,
        reliability: 14,
        pitStopTime: 0.47,
      },
      {
        level: 11,
        speed: 13,
        cornering: 14,
        powerUnit: 12,
        reliability: 15,
        pitStopTime: 0.43,
      },
    ],
  },
  {
    id: 2,
    name: 'Swiftcharge',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        speed: 4,
        cornering: 8,
        powerUnit: 7,
        reliability: 6,
        pitStopTime: 0.92,
      },
      {
        level: 2,
        speed: 5,
        cornering: 10,
        powerUnit: 9,
        reliability: 7,
        pitStopTime: 0.9,
      },
      {
        level: 3,
        speed: 6,
        cornering: 11,
        powerUnit: 10,
        reliability: 8,
        pitStopTime: 0.88,
      },
      {
        level: 4,
        speed: 7,
        cornering: 13,
        powerUnit: 12,
        reliability: 9,
        pitStopTime: 0.86,
      },
      {
        level: 5,
        speed: 8,
        cornering: 14,
        powerUnit: 13,
        reliability: 10,
        pitStopTime: 0.84,
      },
      {
        level: 6,
        speed: 9,
        cornering: 16,
        powerUnit: 15,
        reliability: 11,
        pitStopTime: 0.82,
      },
      {
        level: 7,
        speed: 10,
        cornering: 17,
        powerUnit: 16,
        reliability: 12,
        pitStopTime: 0.8,
      },
      {
        level: 8,
        speed: 11,
        cornering: 19,
        powerUnit: 18,
        reliability: 13,
        pitStopTime: 0.78,
      },
      {
        level: 9,
        speed: 12,
        cornering: 20,
        powerUnit: 19,
        reliability: 14,
        pitStopTime: 0.76,
      },
      {
        level: 10,
        speed: 13,
        cornering: 22,
        powerUnit: 21,
        reliability: 15,
        pitStopTime: 0.73,
      },
      {
        level: 11,
        speed: 14,
        cornering: 23,
        powerUnit: 22,
        reliability: 16,
        pitStopTime: 0.71,
      },
    ],
  },
  {
    id: 3,
    name: 'Spectrum',
    rarity: 'rare',
    series: 4,
    stats: [
      {
        level: 1,
        speed: 8,
        cornering: 11,
        powerUnit: 7,
        reliability: 9,
        pitStopTime: 0.82,
      },
      {
        level: 2,
        speed: 10,
        cornering: 13,
        powerUnit: 9,
        reliability: 11,
        pitStopTime: 0.78,
      },
      {
        level: 3,
        speed: 11,
        cornering: 15,
        powerUnit: 11,
        reliability: 13,
        pitStopTime: 0.75,
      },
      {
        level: 4,
        speed: 13,
        cornering: 16,
        powerUnit: 12,
        reliability: 14,
        pitStopTime: 0.71,
      },
      {
        level: 5,
        speed: 14,
        cornering: 18,
        powerUnit: 14,
        reliability: 16,
        pitStopTime: 0.67,
      },
      {
        level: 6,
        speed: 16,
        cornering: 20,
        powerUnit: 16,
        reliability: 18,
        pitStopTime: 0.64,
      },
      {
        level: 7,
        speed: 17,
        cornering: 22,
        powerUnit: 18,
        reliability: 20,
        pitStopTime: 0.6,
      },
      {
        level: 8,
        speed: 19,
        cornering: 23,
        powerUnit: 19,
        reliability: 21,
        pitStopTime: 0.57,
      },
      {
        level: 9,
        speed: 20,
        cornering: 25,
        powerUnit: 21,
        reliability: 23,
        pitStopTime: 0.53,
      },
    ],
  },
  {
    id: 4,
    name: 'Verdict',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        speed: 16,
        cornering: 7,
        powerUnit: 9,
        reliability: 13,
        pitStopTime: 0.86,
      },
      {
        level: 2,
        speed: 18,
        cornering: 8,
        powerUnit: 10,
        reliability: 15,
        pitStopTime: 0.83,
      },
      {
        level: 3,
        speed: 20,
        cornering: 10,
        powerUnit: 12,
        reliability: 17,
        pitStopTime: 0.8,
      },
      {
        level: 4,
        speed: 22,
        cornering: 11,
        powerUnit: 13,
        reliability: 19,
        pitStopTime: 0.77,
      },
      {
        level: 5,
        speed: 25,
        cornering: 13,
        powerUnit: 14,
        reliability: 22,
        pitStopTime: 0.75,
      },
      {
        level: 6,
        speed: 27,
        cornering: 14,
        powerUnit: 16,
        reliability: 24,
        pitStopTime: 0.72,
      },
      {
        level: 7,
        speed: 29,
        cornering: 15,
        powerUnit: 17,
        reliability: 26,
        pitStopTime: 0.69,
      },
      {
        level: 8,
        speed: 31,
        cornering: 17,
        powerUnit: 19,
        reliability: 28,
        pitStopTime: 0.66,
      },
      {
        level: 9,
        speed: 33,
        cornering: 18,
        powerUnit: 20,
        reliability: 30,
        pitStopTime: 0.63,
      },
    ],
  },
  {
    id: 5,
    name: 'Kick Shift',
    rarity: 'common',
    series: 7,
    stats: [
      {
        level: 1,
        speed: 8,
        cornering: 9,
        powerUnit: 14,
        reliability: 9,
        pitStopTime: 0.76,
      },
      {
        level: 2,
        speed: 9,
        cornering: 10,
        powerUnit: 16,
        reliability: 10,
        pitStopTime: 0.72,
      },
      {
        level: 3,
        speed: 10,
        cornering: 11,
        powerUnit: 17,
        reliability: 11,
        pitStopTime: 0.69,
      },
      {
        level: 4,
        speed: 11,
        cornering: 12,
        powerUnit: 19,
        reliability: 12,
        pitStopTime: 0.66,
      },
      {
        level: 5,
        speed: 12,
        cornering: 13,
        powerUnit: 20,
        reliability: 13,
        pitStopTime: 0.63,
      },
      {
        level: 6,
        speed: 13,
        cornering: 14,
        powerUnit: 22,
        reliability: 14,
        pitStopTime: 0.6,
      },
      {
        level: 7,
        speed: 14,
        cornering: 15,
        powerUnit: 23,
        reliability: 15,
        pitStopTime: 0.57,
      },
      {
        level: 8,
        speed: 15,
        cornering: 16,
        powerUnit: 25,
        reliability: 16,
        pitStopTime: 0.54,
      },
      {
        level: 9,
        speed: 16,
        cornering: 17,
        powerUnit: 26,
        reliability: 17,
        pitStopTime: 0.51,
      },
      {
        level: 10,
        speed: 17,
        cornering: 18,
        powerUnit: 28,
        reliability: 18,
        pitStopTime: 0.48,
      },
      {
        level: 11,
        speed: 18,
        cornering: 19,
        powerUnit: 29,
        reliability: 19,
        pitStopTime: 0.45,
      },
    ],
  },
  {
    id: 6,
    name: 'Vector',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 18,
        powerUnit: 10,
        reliability: 17,
        pitStopTime: 0.8,
      },
      {
        level: 2,
        speed: 14,
        cornering: 21,
        powerUnit: 12,
        reliability: 20,
        pitStopTime: 0.76,
      },
      {
        level: 3,
        speed: 15,
        cornering: 24,
        powerUnit: 13,
        reliability: 22,
        pitStopTime: 0.73,
      },
      {
        level: 4,
        speed: 17,
        cornering: 27,
        powerUnit: 15,
        reliability: 25,
        pitStopTime: 0.69,
      },
      {
        level: 5,
        speed: 19,
        cornering: 29,
        powerUnit: 17,
        reliability: 28,
        pitStopTime: 0.66,
      },
      {
        level: 6,
        speed: 21,
        cornering: 32,
        powerUnit: 19,
        reliability: 31,
        pitStopTime: 0.62,
      },
      {
        level: 7,
        speed: 22,
        cornering: 35,
        powerUnit: 20,
        reliability: 33,
        pitStopTime: 0.59,
      },
      {
        level: 8,
        speed: 24,
        cornering: 38,
        powerUnit: 22,
        reliability: 36,
        pitStopTime: 0.55,
      },
    ],
  },
  {
    id: 7,
    name: 'Voyage',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        speed: 12,
        cornering: 14,
        powerUnit: 11,
        reliability: 13,
        pitStopTime: 0.51,
      },
      {
        level: 2,
        speed: 14,
        cornering: 16,
        powerUnit: 13,
        reliability: 15,
        pitStopTime: 0.44,
      },
      {
        level: 3,
        speed: 15,
        cornering: 18,
        powerUnit: 14,
        reliability: 17,
        pitStopTime: 0.36,
      },
      {
        level: 4,
        speed: 17,
        cornering: 20,
        powerUnit: 16,
        reliability: 19,
        pitStopTime: 0.29,
      },
      {
        level: 5,
        speed: 18,
        cornering: 22,
        powerUnit: 17,
        reliability: 21,
        pitStopTime: 0.22,
      },
      {
        level: 6,
        speed: 20,
        cornering: 24,
        powerUnit: 19,
        reliability: 23,
        pitStopTime: 0.15,
      },
      {
        level: 7,
        speed: 21,
        cornering: 26,
        powerUnit: 20,
        reliability: 25,
        pitStopTime: 0.07,
      },
      {
        level: 8,
        speed: 23,
        cornering: 28,
        powerUnit: 22,
        reliability: 27,
        pitStopTime: 0,
      },
    ],
  },
] as Part[];

const createGearboxes = () => {
  const gearboxesToSave = preparePartData(GEARBOXES);

  console.log('Creating gearboxes file >>');
  createFile('src/features/parts/constants/gearboxes.json', gearboxesToSave);
};

export default createGearboxes;
