/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { prepareDriversData } from './utils';
import type { Driver } from './types';

const DRIVERS: Driver[] = [
  {
    id: 1,
    name: 'Logan Sargeant',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        overtaking: 6,
        defending: 7,
        qualifying: 12,
        raceStart: 14,
        tireManagement: 16,
      },
      {
        level: 2,
        overtaking: 10,
        defending: 11,
        qualifying: 16,
        raceStart: 18,
        tireManagement: 20,
      },
      {
        level: 3,
        overtaking: 13,
        defending: 14,
        qualifying: 19,
        raceStart: 21,
        tireManagement: 23,
      },
      {
        level: 4,
        overtaking: 17,
        defending: 18,
        qualifying: 23,
        raceStart: 25,
        tireManagement: 27,
      },
      {
        level: 5,
        overtaking: 21,
        defending: 22,
        qualifying: 27,
        raceStart: 29,
        tireManagement: 31,
      },
      {
        level: 6,
        overtaking: 25,
        defending: 26,
        qualifying: 31,
        raceStart: 33,
        tireManagement: 35,
      },
      {
        level: 7,
        overtaking: 28,
        defending: 29,
        qualifying: 34,
        raceStart: 36,
        tireManagement: 38,
      },
      {
        level: 8,
        overtaking: 32,
        defending: 33,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 42,
      },
      {
        level: 9,
        overtaking: 36,
        defending: 37,
        qualifying: 42,
        raceStart: 44,
        tireManagement: 46,
      },
      {
        level: 10,
        overtaking: 39,
        defending: 40,
        qualifying: 45,
        raceStart: 47,
        tireManagement: 49,
      },
      {
        level: 11,
        overtaking: 43,
        defending: 44,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 53,
      },
    ],
  },
  {
    id: 2,
    name: 'Oscar Piastri',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        overtaking: 7,
        defending: 11,
        qualifying: 13,
        raceStart: 18,
        tireManagement: 6,
      },
      {
        level: 2,
        overtaking: 11,
        defending: 15,
        qualifying: 17,
        raceStart: 22,
        tireManagement: 10,
      },
      {
        level: 3,
        overtaking: 14,
        defending: 18,
        qualifying: 20,
        raceStart: 25,
        tireManagement: 13,
      },
      {
        level: 4,
        overtaking: 18,
        defending: 22,
        qualifying: 24,
        raceStart: 29,
        tireManagement: 17,
      },
      {
        level: 5,
        overtaking: 22,
        defending: 26,
        qualifying: 28,
        raceStart: 33,
        tireManagement: 21,
      },
      {
        level: 6,
        overtaking: 26,
        defending: 30,
        qualifying: 32,
        raceStart: 37,
        tireManagement: 25,
      },
      {
        level: 7,
        overtaking: 29,
        defending: 33,
        qualifying: 35,
        raceStart: 40,
        tireManagement: 28,
      },
      {
        level: 8,
        overtaking: 33,
        defending: 37,
        qualifying: 39,
        raceStart: 44,
        tireManagement: 32,
      },
      {
        level: 9,
        overtaking: 37,
        defending: 41,
        qualifying: 43,
        raceStart: 48,
        tireManagement: 36,
      },
      {
        level: 10,
        overtaking: 40,
        defending: 44,
        qualifying: 46,
        raceStart: 51,
        tireManagement: 39,
      },
      {
        level: 11,
        overtaking: 44,
        defending: 48,
        qualifying: 50,
        raceStart: 55,
        tireManagement: 43,
      },
    ],
  },
  {
    id: 3,
    name: 'Nico Hulkenberg',
    rarity: 'common',
    series: 1,
    stats: [
      {
        level: 1,
        overtaking: 10,
        defending: 15,
        qualifying: 18,
        raceStart: 5,
        tireManagement: 7,
      },
      {
        level: 2,
        overtaking: 14,
        defending: 19,
        qualifying: 22,
        raceStart: 9,
        tireManagement: 11,
      },
      {
        level: 3,
        overtaking: 17,
        defending: 22,
        qualifying: 25,
        raceStart: 12,
        tireManagement: 14,
      },
      {
        level: 4,
        overtaking: 21,
        defending: 26,
        qualifying: 29,
        raceStart: 16,
        tireManagement: 18,
      },
      {
        level: 5,
        overtaking: 25,
        defending: 30,
        qualifying: 33,
        raceStart: 20,
        tireManagement: 22,
      },
      {
        level: 6,
        overtaking: 29,
        defending: 34,
        qualifying: 37,
        raceStart: 24,
        tireManagement: 26,
      },
      {
        level: 7,
        overtaking: 32,
        defending: 37,
        qualifying: 40,
        raceStart: 27,
        tireManagement: 29,
      },
      {
        level: 8,
        overtaking: 36,
        defending: 41,
        qualifying: 44,
        raceStart: 31,
        tireManagement: 33,
      },
      {
        level: 9,
        overtaking: 40,
        defending: 45,
        qualifying: 48,
        raceStart: 35,
        tireManagement: 37,
      },
      {
        level: 10,
        overtaking: 43,
        defending: 48,
        qualifying: 51,
        raceStart: 38,
        tireManagement: 40,
      },
      {
        level: 11,
        overtaking: 47,
        defending: 52,
        qualifying: 55,
        raceStart: 42,
        tireManagement: 44,
      },
    ],
  },
  {
    id: 4,
    name: 'Nyck De Vries',
    rarity: 'rare',
    series: 1,
    stats: [
      {
        level: 1,
        overtaking: 17,
        defending: 19,
        qualifying: 6,
        raceStart: 11,
        tireManagement: 12,
      },
      {
        level: 2,
        overtaking: 22,
        defending: 24,
        qualifying: 11,
        raceStart: 16,
        tireManagement: 17,
      },
      {
        level: 3,
        overtaking: 26,
        defending: 28,
        qualifying: 15,
        raceStart: 20,
        tireManagement: 21,
      },
      {
        level: 4,
        overtaking: 31,
        defending: 33,
        qualifying: 20,
        raceStart: 25,
        tireManagement: 26,
      },
      {
        level: 5,
        overtaking: 36,
        defending: 38,
        qualifying: 25,
        raceStart: 30,
        tireManagement: 31,
      },
      {
        level: 6,
        overtaking: 40,
        defending: 42,
        qualifying: 29,
        raceStart: 34,
        tireManagement: 35,
      },
      {
        level: 7,
        overtaking: 45,
        defending: 47,
        qualifying: 34,
        raceStart: 39,
        tireManagement: 40,
      },
      {
        level: 8,
        overtaking: 49,
        defending: 51,
        qualifying: 38,
        raceStart: 43,
        tireManagement: 44,
      },
      {
        level: 9,
        overtaking: 54,
        defending: 56,
        qualifying: 43,
        raceStart: 48,
        tireManagement: 49,
      },
    ],
  },
  {
    id: 5,
    name: 'Alex Albon',
    rarity: 'epic',
    series: 1,
    stats: [
      {
        level: 1,
        overtaking: 21,
        defending: 10,
        qualifying: 12,
        raceStart: 14,
        tireManagement: 18,
      },
      {
        level: 2,
        overtaking: 26,
        defending: 15,
        qualifying: 17,
        raceStart: 19,
        tireManagement: 23,
      },
      {
        level: 3,
        overtaking: 32,
        defending: 21,
        qualifying: 23,
        raceStart: 25,
        tireManagement: 29,
      },
      {
        level: 4,
        overtaking: 37,
        defending: 26,
        qualifying: 28,
        raceStart: 30,
        tireManagement: 34,
      },
      {
        level: 5,
        overtaking: 42,
        defending: 31,
        qualifying: 33,
        raceStart: 35,
        tireManagement: 39,
      },
      {
        level: 6,
        overtaking: 47,
        defending: 36,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 44,
      },
      {
        level: 7,
        overtaking: 53,
        defending: 42,
        qualifying: 44,
        raceStart: 46,
        tireManagement: 50,
      },
      {
        level: 8,
        overtaking: 58,
        defending: 47,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 55,
      },
    ],
  },
  {
    id: 6,
    name: 'Nyck De Vries',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        overtaking: 19,
        defending: 21,
        qualifying: 8,
        raceStart: 13,
        tireManagement: 14,
      },
      {
        level: 2,
        overtaking: 23,
        defending: 25,
        qualifying: 12,
        raceStart: 17,
        tireManagement: 18,
      },
      {
        level: 3,
        overtaking: 26,
        defending: 28,
        qualifying: 15,
        raceStart: 20,
        tireManagement: 21,
      },
      {
        level: 4,
        overtaking: 30,
        defending: 32,
        qualifying: 19,
        raceStart: 24,
        tireManagement: 25,
      },
      {
        level: 5,
        overtaking: 34,
        defending: 36,
        qualifying: 23,
        raceStart: 28,
        tireManagement: 29,
      },
      {
        level: 6,
        overtaking: 38,
        defending: 40,
        qualifying: 27,
        raceStart: 32,
        tireManagement: 33,
      },
      {
        level: 7,
        overtaking: 41,
        defending: 43,
        qualifying: 30,
        raceStart: 35,
        tireManagement: 36,
      },
      {
        level: 8,
        overtaking: 45,
        defending: 47,
        qualifying: 34,
        raceStart: 39,
        tireManagement: 40,
      },
      {
        level: 9,
        overtaking: 49,
        defending: 51,
        qualifying: 38,
        raceStart: 43,
        tireManagement: 44,
      },
      {
        level: 10,
        overtaking: 52,
        defending: 54,
        qualifying: 41,
        raceStart: 46,
        tireManagement: 47,
      },
      {
        level: 11,
        overtaking: 56,
        defending: 58,
        qualifying: 45,
        raceStart: 50,
        tireManagement: 51,
      },
    ],
  },
  {
    id: 7,
    name: 'Alex Albon',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        overtaking: 21,
        defending: 10,
        qualifying: 12,
        raceStart: 14,
        tireManagement: 18,
      },
      {
        level: 2,
        overtaking: 25,
        defending: 14,
        qualifying: 16,
        raceStart: 18,
        tireManagement: 22,
      },
      {
        level: 3,
        overtaking: 28,
        defending: 17,
        qualifying: 19,
        raceStart: 21,
        tireManagement: 25,
      },
      {
        level: 4,
        overtaking: 32,
        defending: 21,
        qualifying: 23,
        raceStart: 25,
        tireManagement: 29,
      },
      {
        level: 5,
        overtaking: 36,
        defending: 25,
        qualifying: 27,
        raceStart: 29,
        tireManagement: 33,
      },
      {
        level: 6,
        overtaking: 40,
        defending: 29,
        qualifying: 31,
        raceStart: 33,
        tireManagement: 37,
      },
      {
        level: 7,
        overtaking: 43,
        defending: 32,
        qualifying: 34,
        raceStart: 36,
        tireManagement: 40,
      },
      {
        level: 8,
        overtaking: 47,
        defending: 36,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 44,
      },
      {
        level: 9,
        overtaking: 51,
        defending: 40,
        qualifying: 42,
        raceStart: 44,
        tireManagement: 48,
      },
      {
        level: 10,
        overtaking: 54,
        defending: 43,
        qualifying: 45,
        raceStart: 47,
        tireManagement: 51,
      },
      {
        level: 11,
        overtaking: 58,
        defending: 47,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 55,
      },
    ],
  },
  {
    id: 8,
    name: 'Yuki Tsunoda',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        overtaking: 14,
        defending: 17,
        qualifying: 9,
        raceStart: 22,
        tireManagement: 13,
      },
      {
        level: 2,
        overtaking: 18,
        defending: 21,
        qualifying: 13,
        raceStart: 26,
        tireManagement: 17,
      },
      {
        level: 3,
        overtaking: 21,
        defending: 24,
        qualifying: 16,
        raceStart: 29,
        tireManagement: 20,
      },
      {
        level: 4,
        overtaking: 25,
        defending: 28,
        qualifying: 20,
        raceStart: 33,
        tireManagement: 24,
      },
      {
        level: 5,
        overtaking: 29,
        defending: 32,
        qualifying: 24,
        raceStart: 37,
        tireManagement: 28,
      },
      {
        level: 6,
        overtaking: 33,
        defending: 36,
        qualifying: 28,
        raceStart: 41,
        tireManagement: 32,
      },
      {
        level: 7,
        overtaking: 36,
        defending: 39,
        qualifying: 31,
        raceStart: 44,
        tireManagement: 35,
      },
      {
        level: 8,
        overtaking: 40,
        defending: 43,
        qualifying: 35,
        raceStart: 48,
        tireManagement: 39,
      },
      {
        level: 9,
        overtaking: 44,
        defending: 47,
        qualifying: 39,
        raceStart: 52,
        tireManagement: 43,
      },
      {
        level: 10,
        overtaking: 47,
        defending: 50,
        qualifying: 42,
        raceStart: 55,
        tireManagement: 46,
      },
      {
        level: 11,
        overtaking: 51,
        defending: 54,
        qualifying: 46,
        raceStart: 59,
        tireManagement: 50,
      },
    ],
  },
  {
    id: 9,
    name: 'Zhou Guanyu',
    rarity: 'common',
    series: 2,
    stats: [
      {
        level: 1,
        overtaking: 12,
        defending: 15,
        qualifying: 19,
        raceStart: 9,
        tireManagement: 20,
      },
      {
        level: 2,
        overtaking: 16,
        defending: 19,
        qualifying: 23,
        raceStart: 13,
        tireManagement: 24,
      },
      {
        level: 3,
        overtaking: 19,
        defending: 22,
        qualifying: 26,
        raceStart: 16,
        tireManagement: 27,
      },
      {
        level: 4,
        overtaking: 23,
        defending: 26,
        qualifying: 30,
        raceStart: 20,
        tireManagement: 31,
      },
      {
        level: 5,
        overtaking: 27,
        defending: 30,
        qualifying: 34,
        raceStart: 24,
        tireManagement: 35,
      },
      {
        level: 6,
        overtaking: 31,
        defending: 34,
        qualifying: 38,
        raceStart: 28,
        tireManagement: 39,
      },
      {
        level: 7,
        overtaking: 34,
        defending: 37,
        qualifying: 41,
        raceStart: 31,
        tireManagement: 42,
      },
      {
        level: 8,
        overtaking: 38,
        defending: 41,
        qualifying: 45,
        raceStart: 35,
        tireManagement: 46,
      },
      {
        level: 9,
        overtaking: 42,
        defending: 45,
        qualifying: 49,
        raceStart: 39,
        tireManagement: 50,
      },
      {
        level: 10,
        overtaking: 45,
        defending: 48,
        qualifying: 52,
        raceStart: 42,
        tireManagement: 53,
      },
      {
        level: 11,
        overtaking: 49,
        defending: 52,
        qualifying: 56,
        raceStart: 46,
        tireManagement: 57,
      },
    ],
  },
  {
    id: 10,
    name: 'Logan Sargeant',
    rarity: 'epic',
    series: 2,
    stats: [
      {
        level: 1,
        overtaking: 14,
        defending: 15,
        qualifying: 20,
        raceStart: 22,
        tireManagement: 24,
      },
      {
        level: 2,
        overtaking: 19,
        defending: 20,
        qualifying: 25,
        raceStart: 27,
        tireManagement: 29,
      },
      {
        level: 3,
        overtaking: 25,
        defending: 26,
        qualifying: 31,
        raceStart: 33,
        tireManagement: 35,
      },
      {
        level: 4,
        overtaking: 30,
        defending: 31,
        qualifying: 36,
        raceStart: 38,
        tireManagement: 40,
      },
      {
        level: 5,
        overtaking: 35,
        defending: 36,
        qualifying: 41,
        raceStart: 43,
        tireManagement: 45,
      },
      {
        level: 6,
        overtaking: 40,
        defending: 41,
        qualifying: 46,
        raceStart: 48,
        tireManagement: 50,
      },
      {
        level: 7,
        overtaking: 46,
        defending: 47,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 56,
      },
      {
        level: 8,
        overtaking: 51,
        defending: 52,
        qualifying: 57,
        raceStart: 59,
        tireManagement: 61,
      },
    ],
  },
  {
    id: 11,
    name: 'Valtteri Bottas',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        overtaking: 26,
        defending: 16,
        qualifying: 19,
        raceStart: 21,
        tireManagement: 13,
      },
      {
        level: 2,
        overtaking: 30,
        defending: 20,
        qualifying: 23,
        raceStart: 25,
        tireManagement: 17,
      },
      {
        level: 3,
        overtaking: 33,
        defending: 23,
        qualifying: 26,
        raceStart: 28,
        tireManagement: 20,
      },
      {
        level: 4,
        overtaking: 37,
        defending: 27,
        qualifying: 30,
        raceStart: 32,
        tireManagement: 24,
      },
      {
        level: 5,
        overtaking: 41,
        defending: 31,
        qualifying: 34,
        raceStart: 36,
        tireManagement: 28,
      },
      {
        level: 6,
        overtaking: 45,
        defending: 35,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 32,
      },
      {
        level: 7,
        overtaking: 48,
        defending: 38,
        qualifying: 41,
        raceStart: 43,
        tireManagement: 35,
      },
      {
        level: 8,
        overtaking: 52,
        defending: 42,
        qualifying: 45,
        raceStart: 47,
        tireManagement: 39,
      },
      {
        level: 9,
        overtaking: 56,
        defending: 46,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 43,
      },
      {
        level: 10,
        overtaking: 59,
        defending: 49,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 46,
      },
      {
        level: 11,
        overtaking: 63,
        defending: 53,
        qualifying: 56,
        raceStart: 58,
        tireManagement: 50,
      },
    ],
  },
  {
    id: 12,
    name: 'Kevin Magnussen',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        overtaking: 12,
        defending: 26,
        qualifying: 16,
        raceStart: 20,
        tireManagement: 21,
      },
      {
        level: 2,
        overtaking: 16,
        defending: 30,
        qualifying: 20,
        raceStart: 24,
        tireManagement: 25,
      },
      {
        level: 3,
        overtaking: 19,
        defending: 33,
        qualifying: 23,
        raceStart: 27,
        tireManagement: 28,
      },
      {
        level: 4,
        overtaking: 23,
        defending: 37,
        qualifying: 27,
        raceStart: 31,
        tireManagement: 32,
      },
      {
        level: 5,
        overtaking: 27,
        defending: 41,
        qualifying: 31,
        raceStart: 35,
        tireManagement: 36,
      },
      {
        level: 6,
        overtaking: 31,
        defending: 45,
        qualifying: 35,
        raceStart: 39,
        tireManagement: 40,
      },
      {
        level: 7,
        overtaking: 34,
        defending: 48,
        qualifying: 38,
        raceStart: 42,
        tireManagement: 43,
      },
      {
        level: 8,
        overtaking: 38,
        defending: 52,
        qualifying: 42,
        raceStart: 46,
        tireManagement: 47,
      },
      {
        level: 9,
        overtaking: 42,
        defending: 56,
        qualifying: 46,
        raceStart: 50,
        tireManagement: 51,
      },
      {
        level: 10,
        overtaking: 45,
        defending: 59,
        qualifying: 49,
        raceStart: 53,
        tireManagement: 54,
      },
      {
        level: 11,
        overtaking: 49,
        defending: 63,
        qualifying: 53,
        raceStart: 57,
        tireManagement: 58,
      },
    ],
  },
  {
    id: 13,
    name: 'Esteban Ocon',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        overtaking: 23,
        defending: 12,
        qualifying: 24,
        raceStart: 17,
        tireManagement: 19,
      },
      {
        level: 2,
        overtaking: 27,
        defending: 16,
        qualifying: 28,
        raceStart: 21,
        tireManagement: 23,
      },
      {
        level: 3,
        overtaking: 30,
        defending: 19,
        qualifying: 31,
        raceStart: 24,
        tireManagement: 26,
      },
      {
        level: 4,
        overtaking: 34,
        defending: 23,
        qualifying: 35,
        raceStart: 28,
        tireManagement: 30,
      },
      {
        level: 5,
        overtaking: 38,
        defending: 27,
        qualifying: 39,
        raceStart: 32,
        tireManagement: 34,
      },
      {
        level: 6,
        overtaking: 42,
        defending: 31,
        qualifying: 43,
        raceStart: 36,
        tireManagement: 38,
      },
      {
        level: 7,
        overtaking: 45,
        defending: 34,
        qualifying: 46,
        raceStart: 39,
        tireManagement: 41,
      },
      {
        level: 8,
        overtaking: 49,
        defending: 38,
        qualifying: 50,
        raceStart: 43,
        tireManagement: 45,
      },
      {
        level: 9,
        overtaking: 53,
        defending: 42,
        qualifying: 54,
        raceStart: 47,
        tireManagement: 49,
      },
      {
        level: 10,
        overtaking: 56,
        defending: 45,
        qualifying: 57,
        raceStart: 50,
        tireManagement: 52,
      },
      {
        level: 11,
        overtaking: 60,
        defending: 49,
        qualifying: 61,
        raceStart: 54,
        tireManagement: 56,
      },
    ],
  },
  {
    id: 14,
    name: 'Pierre Gasly',
    rarity: 'common',
    series: 3,
    stats: [
      {
        level: 1,
        overtaking: 18,
        defending: 23,
        qualifying: 13,
        raceStart: 15,
        tireManagement: 26,
      },
      {
        level: 2,
        overtaking: 22,
        defending: 27,
        qualifying: 17,
        raceStart: 19,
        tireManagement: 30,
      },
      {
        level: 3,
        overtaking: 25,
        defending: 30,
        qualifying: 20,
        raceStart: 22,
        tireManagement: 33,
      },
      {
        level: 4,
        overtaking: 29,
        defending: 34,
        qualifying: 24,
        raceStart: 26,
        tireManagement: 37,
      },
      {
        level: 5,
        overtaking: 33,
        defending: 38,
        qualifying: 28,
        raceStart: 30,
        tireManagement: 41,
      },
      {
        level: 6,
        overtaking: 37,
        defending: 42,
        qualifying: 32,
        raceStart: 34,
        tireManagement: 45,
      },
      {
        level: 7,
        overtaking: 40,
        defending: 45,
        qualifying: 35,
        raceStart: 37,
        tireManagement: 48,
      },
      {
        level: 8,
        overtaking: 44,
        defending: 49,
        qualifying: 39,
        raceStart: 41,
        tireManagement: 52,
      },
      {
        level: 9,
        overtaking: 48,
        defending: 53,
        qualifying: 43,
        raceStart: 45,
        tireManagement: 56,
      },
      {
        level: 10,
        overtaking: 51,
        defending: 56,
        qualifying: 46,
        raceStart: 48,
        tireManagement: 59,
      },
      {
        level: 11,
        overtaking: 55,
        defending: 60,
        qualifying: 50,
        raceStart: 52,
        tireManagement: 63,
      },
    ],
  },
  {
    id: 15,
    name: 'Oscar Piastri',
    rarity: 'rare',
    series: 3,
    stats: [
      {
        level: 1,
        overtaking: 16,
        defending: 20,
        qualifying: 22,
        raceStart: 27,
        tireManagement: 15,
      },
      {
        level: 2,
        overtaking: 21,
        defending: 25,
        qualifying: 27,
        raceStart: 32,
        tireManagement: 20,
      },
      {
        level: 3,
        overtaking: 26,
        defending: 30,
        qualifying: 32,
        raceStart: 37,
        tireManagement: 25,
      },
      {
        level: 4,
        overtaking: 30,
        defending: 34,
        qualifying: 36,
        raceStart: 41,
        tireManagement: 29,
      },
      {
        level: 5,
        overtaking: 35,
        defending: 39,
        qualifying: 41,
        raceStart: 46,
        tireManagement: 34,
      },
      {
        level: 6,
        overtaking: 40,
        defending: 44,
        qualifying: 46,
        raceStart: 51,
        tireManagement: 39,
      },
      {
        level: 7,
        overtaking: 45,
        defending: 49,
        qualifying: 51,
        raceStart: 56,
        tireManagement: 44,
      },
      {
        level: 8,
        overtaking: 49,
        defending: 53,
        qualifying: 55,
        raceStart: 60,
        tireManagement: 48,
      },
      {
        level: 9,
        overtaking: 54,
        defending: 58,
        qualifying: 60,
        raceStart: 65,
        tireManagement: 53,
      },
    ],
  },
  {
    id: 16,
    name: 'Lance Stroll',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        overtaking: 25,
        defending: 16,
        qualifying: 20,
        raceStart: 27,
        tireManagement: 22,
      },
      {
        level: 2,
        overtaking: 29,
        defending: 20,
        qualifying: 24,
        raceStart: 31,
        tireManagement: 26,
      },
      {
        level: 3,
        overtaking: 33,
        defending: 24,
        qualifying: 28,
        raceStart: 35,
        tireManagement: 30,
      },
      {
        level: 4,
        overtaking: 36,
        defending: 27,
        qualifying: 31,
        raceStart: 38,
        tireManagement: 33,
      },
      {
        level: 5,
        overtaking: 40,
        defending: 31,
        qualifying: 35,
        raceStart: 42,
        tireManagement: 37,
      },
      {
        level: 6,
        overtaking: 44,
        defending: 35,
        qualifying: 39,
        raceStart: 46,
        tireManagement: 41,
      },
      {
        level: 7,
        overtaking: 48,
        defending: 39,
        qualifying: 43,
        raceStart: 50,
        tireManagement: 45,
      },
      {
        level: 8,
        overtaking: 52,
        defending: 43,
        qualifying: 47,
        raceStart: 54,
        tireManagement: 49,
      },
      {
        level: 9,
        overtaking: 55,
        defending: 46,
        qualifying: 50,
        raceStart: 57,
        tireManagement: 52,
      },
      {
        level: 10,
        overtaking: 59,
        defending: 50,
        qualifying: 54,
        raceStart: 61,
        tireManagement: 56,
      },
      {
        level: 11,
        overtaking: 63,
        defending: 54,
        qualifying: 58,
        raceStart: 65,
        tireManagement: 60,
      },
    ],
  },
  {
    id: 17,
    name: 'Sergio Perez',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        overtaking: 18,
        defending: 29,
        qualifying: 22,
        raceStart: 24,
        tireManagement: 17,
      },
      {
        level: 2,
        overtaking: 22,
        defending: 33,
        qualifying: 26,
        raceStart: 28,
        tireManagement: 21,
      },
      {
        level: 3,
        overtaking: 26,
        defending: 37,
        qualifying: 30,
        raceStart: 32,
        tireManagement: 25,
      },
      {
        level: 4,
        overtaking: 29,
        defending: 40,
        qualifying: 33,
        raceStart: 35,
        tireManagement: 28,
      },
      {
        level: 5,
        overtaking: 33,
        defending: 44,
        qualifying: 37,
        raceStart: 39,
        tireManagement: 32,
      },
      {
        level: 6,
        overtaking: 37,
        defending: 48,
        qualifying: 41,
        raceStart: 43,
        tireManagement: 36,
      },
      {
        level: 7,
        overtaking: 41,
        defending: 52,
        qualifying: 45,
        raceStart: 47,
        tireManagement: 40,
      },
      {
        level: 8,
        overtaking: 45,
        defending: 56,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 44,
      },
      {
        level: 9,
        overtaking: 48,
        defending: 59,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 47,
      },
      {
        level: 10,
        overtaking: 52,
        defending: 63,
        qualifying: 56,
        raceStart: 58,
        tireManagement: 51,
      },
      {
        level: 11,
        overtaking: 56,
        defending: 67,
        qualifying: 60,
        raceStart: 62,
        tireManagement: 55,
      },
    ],
  },
  {
    id: 18,
    name: 'Carlos Sainz',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        overtaking: 17,
        defending: 18,
        qualifying: 28,
        raceStart: 23,
        tireManagement: 24,
      },
      {
        level: 2,
        overtaking: 21,
        defending: 22,
        qualifying: 32,
        raceStart: 27,
        tireManagement: 28,
      },
      {
        level: 3,
        overtaking: 25,
        defending: 26,
        qualifying: 36,
        raceStart: 31,
        tireManagement: 32,
      },
      {
        level: 4,
        overtaking: 28,
        defending: 29,
        qualifying: 39,
        raceStart: 34,
        tireManagement: 35,
      },
      {
        level: 5,
        overtaking: 32,
        defending: 33,
        qualifying: 43,
        raceStart: 38,
        tireManagement: 39,
      },
      {
        level: 6,
        overtaking: 36,
        defending: 37,
        qualifying: 47,
        raceStart: 42,
        tireManagement: 43,
      },
      {
        level: 7,
        overtaking: 40,
        defending: 41,
        qualifying: 51,
        raceStart: 46,
        tireManagement: 47,
      },
      {
        level: 8,
        overtaking: 44,
        defending: 45,
        qualifying: 55,
        raceStart: 50,
        tireManagement: 51,
      },
      {
        level: 9,
        overtaking: 47,
        defending: 48,
        qualifying: 58,
        raceStart: 53,
        tireManagement: 54,
      },
      {
        level: 10,
        overtaking: 51,
        defending: 52,
        qualifying: 62,
        raceStart: 57,
        tireManagement: 58,
      },
      {
        level: 11,
        overtaking: 55,
        defending: 56,
        qualifying: 66,
        raceStart: 61,
        tireManagement: 62,
      },
    ],
  },
  {
    id: 19,
    name: 'George Russell',
    rarity: 'common',
    series: 4,
    stats: [
      {
        level: 1,
        overtaking: 28,
        defending: 23,
        qualifying: 24,
        raceStart: 16,
        tireManagement: 19,
      },
      {
        level: 2,
        overtaking: 32,
        defending: 27,
        qualifying: 28,
        raceStart: 20,
        tireManagement: 23,
      },
      {
        level: 3,
        overtaking: 36,
        defending: 31,
        qualifying: 32,
        raceStart: 24,
        tireManagement: 27,
      },
      {
        level: 4,
        overtaking: 39,
        defending: 34,
        qualifying: 35,
        raceStart: 27,
        tireManagement: 30,
      },
      {
        level: 5,
        overtaking: 43,
        defending: 38,
        qualifying: 39,
        raceStart: 31,
        tireManagement: 34,
      },
      {
        level: 6,
        overtaking: 47,
        defending: 42,
        qualifying: 43,
        raceStart: 35,
        tireManagement: 38,
      },
      {
        level: 7,
        overtaking: 51,
        defending: 46,
        qualifying: 47,
        raceStart: 39,
        tireManagement: 42,
      },
      {
        level: 8,
        overtaking: 55,
        defending: 50,
        qualifying: 51,
        raceStart: 43,
        tireManagement: 46,
      },
      {
        level: 9,
        overtaking: 58,
        defending: 53,
        qualifying: 54,
        raceStart: 46,
        tireManagement: 49,
      },
      {
        level: 10,
        overtaking: 62,
        defending: 57,
        qualifying: 58,
        raceStart: 50,
        tireManagement: 53,
      },
      {
        level: 11,
        overtaking: 66,
        defending: 61,
        qualifying: 62,
        raceStart: 54,
        tireManagement: 57,
      },
    ],
  },
  {
    id: 20,
    name: 'Oscar Piastri',
    rarity: 'epic',
    series: 4,
    stats: [
      {
        level: 1,
        overtaking: 22,
        defending: 26,
        qualifying: 28,
        raceStart: 33,
        tireManagement: 21,
      },
      {
        level: 2,
        overtaking: 27,
        defending: 31,
        qualifying: 33,
        raceStart: 38,
        tireManagement: 26,
      },
      {
        level: 3,
        overtaking: 33,
        defending: 37,
        qualifying: 39,
        raceStart: 44,
        tireManagement: 32,
      },
      {
        level: 4,
        overtaking: 38,
        defending: 42,
        qualifying: 44,
        raceStart: 49,
        tireManagement: 37,
      },
      {
        level: 5,
        overtaking: 43,
        defending: 47,
        qualifying: 49,
        raceStart: 54,
        tireManagement: 42,
      },
      {
        level: 6,
        overtaking: 48,
        defending: 52,
        qualifying: 54,
        raceStart: 59,
        tireManagement: 47,
      },
      {
        level: 7,
        overtaking: 54,
        defending: 58,
        qualifying: 60,
        raceStart: 65,
        tireManagement: 53,
      },
      {
        level: 8,
        overtaking: 59,
        defending: 63,
        qualifying: 65,
        raceStart: 70,
        tireManagement: 58,
      },
    ],
  },
  {
    id: 21,
    name: 'Fernando Alonso',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        overtaking: 32,
        defending: 25,
        qualifying: 22,
        raceStart: 30,
        tireManagement: 21,
      },
      {
        level: 2,
        overtaking: 36,
        defending: 29,
        qualifying: 26,
        raceStart: 34,
        tireManagement: 25,
      },
      {
        level: 3,
        overtaking: 39,
        defending: 32,
        qualifying: 29,
        raceStart: 37,
        tireManagement: 28,
      },
      {
        level: 4,
        overtaking: 43,
        defending: 36,
        qualifying: 33,
        raceStart: 41,
        tireManagement: 32,
      },
      {
        level: 5,
        overtaking: 47,
        defending: 40,
        qualifying: 37,
        raceStart: 45,
        tireManagement: 36,
      },
      {
        level: 6,
        overtaking: 51,
        defending: 44,
        qualifying: 41,
        raceStart: 49,
        tireManagement: 40,
      },
      {
        level: 7,
        overtaking: 54,
        defending: 47,
        qualifying: 44,
        raceStart: 52,
        tireManagement: 43,
      },
      {
        level: 8,
        overtaking: 58,
        defending: 51,
        qualifying: 48,
        raceStart: 56,
        tireManagement: 47,
      },
      {
        level: 9,
        overtaking: 62,
        defending: 55,
        qualifying: 52,
        raceStart: 60,
        tireManagement: 51,
      },
      {
        level: 10,
        overtaking: 65,
        defending: 58,
        qualifying: 55,
        raceStart: 63,
        tireManagement: 54,
      },
      {
        level: 11,
        overtaking: 69,
        defending: 62,
        qualifying: 59,
        raceStart: 67,
        tireManagement: 58,
      },
    ],
  },
  {
    id: 22,
    name: 'Lando Norris',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        overtaking: 30,
        defending: 19,
        qualifying: 24,
        raceStart: 25,
        tireManagement: 32,
      },
      {
        level: 2,
        overtaking: 34,
        defending: 23,
        qualifying: 28,
        raceStart: 29,
        tireManagement: 36,
      },
      {
        level: 3,
        overtaking: 37,
        defending: 26,
        qualifying: 31,
        raceStart: 32,
        tireManagement: 39,
      },
      {
        level: 4,
        overtaking: 41,
        defending: 30,
        qualifying: 35,
        raceStart: 36,
        tireManagement: 43,
      },
      {
        level: 5,
        overtaking: 45,
        defending: 34,
        qualifying: 39,
        raceStart: 40,
        tireManagement: 47,
      },
      {
        level: 6,
        overtaking: 49,
        defending: 38,
        qualifying: 43,
        raceStart: 44,
        tireManagement: 51,
      },
      {
        level: 7,
        overtaking: 52,
        defending: 41,
        qualifying: 46,
        raceStart: 47,
        tireManagement: 54,
      },
      {
        level: 8,
        overtaking: 56,
        defending: 45,
        qualifying: 50,
        raceStart: 51,
        tireManagement: 58,
      },
      {
        level: 9,
        overtaking: 60,
        defending: 49,
        qualifying: 54,
        raceStart: 55,
        tireManagement: 62,
      },
      {
        level: 10,
        overtaking: 63,
        defending: 52,
        qualifying: 57,
        raceStart: 58,
        tireManagement: 65,
      },
      {
        level: 11,
        overtaking: 67,
        defending: 56,
        qualifying: 61,
        raceStart: 62,
        tireManagement: 69,
      },
    ],
  },
  {
    id: 23,
    name: 'Max Verstappen',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        overtaking: 30,
        defending: 19,
        qualifying: 32,
        raceStart: 22,
        tireManagement: 27,
      },
      {
        level: 2,
        overtaking: 34,
        defending: 23,
        qualifying: 36,
        raceStart: 26,
        tireManagement: 31,
      },
      {
        level: 3,
        overtaking: 37,
        defending: 26,
        qualifying: 39,
        raceStart: 29,
        tireManagement: 34,
      },
      {
        level: 4,
        overtaking: 41,
        defending: 30,
        qualifying: 43,
        raceStart: 33,
        tireManagement: 38,
      },
      {
        level: 5,
        overtaking: 45,
        defending: 34,
        qualifying: 47,
        raceStart: 37,
        tireManagement: 42,
      },
      {
        level: 6,
        overtaking: 49,
        defending: 38,
        qualifying: 51,
        raceStart: 41,
        tireManagement: 46,
      },
      {
        level: 7,
        overtaking: 52,
        defending: 41,
        qualifying: 54,
        raceStart: 44,
        tireManagement: 49,
      },
      {
        level: 8,
        overtaking: 56,
        defending: 45,
        qualifying: 58,
        raceStart: 48,
        tireManagement: 53,
      },
      {
        level: 9,
        overtaking: 60,
        defending: 49,
        qualifying: 62,
        raceStart: 52,
        tireManagement: 57,
      },
      {
        level: 10,
        overtaking: 63,
        defending: 52,
        qualifying: 65,
        raceStart: 55,
        tireManagement: 60,
      },
      {
        level: 11,
        overtaking: 67,
        defending: 56,
        qualifying: 69,
        raceStart: 59,
        tireManagement: 64,
      },
    ],
  },
  {
    id: 24,
    name: 'Charles Leclerc',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        overtaking: 26,
        defending: 32,
        qualifying: 30,
        raceStart: 20,
        tireManagement: 22,
      },
      {
        level: 2,
        overtaking: 30,
        defending: 36,
        qualifying: 34,
        raceStart: 24,
        tireManagement: 26,
      },
      {
        level: 3,
        overtaking: 33,
        defending: 39,
        qualifying: 37,
        raceStart: 27,
        tireManagement: 29,
      },
      {
        level: 4,
        overtaking: 37,
        defending: 43,
        qualifying: 41,
        raceStart: 31,
        tireManagement: 33,
      },
      {
        level: 5,
        overtaking: 41,
        defending: 47,
        qualifying: 45,
        raceStart: 35,
        tireManagement: 37,
      },
      {
        level: 6,
        overtaking: 45,
        defending: 51,
        qualifying: 49,
        raceStart: 39,
        tireManagement: 41,
      },
      {
        level: 7,
        overtaking: 48,
        defending: 54,
        qualifying: 52,
        raceStart: 42,
        tireManagement: 44,
      },
      {
        level: 8,
        overtaking: 52,
        defending: 58,
        qualifying: 56,
        raceStart: 46,
        tireManagement: 48,
      },
      {
        level: 9,
        overtaking: 56,
        defending: 62,
        qualifying: 60,
        raceStart: 50,
        tireManagement: 52,
      },
      {
        level: 10,
        overtaking: 59,
        defending: 65,
        qualifying: 63,
        raceStart: 53,
        tireManagement: 55,
      },
      {
        level: 11,
        overtaking: 63,
        defending: 69,
        qualifying: 67,
        raceStart: 57,
        tireManagement: 59,
      },
    ],
  },
  {
    id: 25,
    name: 'Lewis Hamilton',
    rarity: 'common',
    series: 5,
    stats: [
      {
        level: 1,
        overtaking: 19,
        defending: 24,
        qualifying: 27,
        raceStart: 32,
        tireManagement: 28,
      },
      {
        level: 2,
        overtaking: 23,
        defending: 28,
        qualifying: 31,
        raceStart: 36,
        tireManagement: 32,
      },
      {
        level: 3,
        overtaking: 26,
        defending: 31,
        qualifying: 34,
        raceStart: 39,
        tireManagement: 35,
      },
      {
        level: 4,
        overtaking: 30,
        defending: 35,
        qualifying: 38,
        raceStart: 43,
        tireManagement: 39,
      },
      {
        level: 5,
        overtaking: 34,
        defending: 39,
        qualifying: 42,
        raceStart: 47,
        tireManagement: 43,
      },
      {
        level: 6,
        overtaking: 38,
        defending: 43,
        qualifying: 46,
        raceStart: 51,
        tireManagement: 47,
      },
      {
        level: 7,
        overtaking: 41,
        defending: 46,
        qualifying: 49,
        raceStart: 54,
        tireManagement: 50,
      },
      {
        level: 8,
        overtaking: 45,
        defending: 50,
        qualifying: 53,
        raceStart: 58,
        tireManagement: 54,
      },
      {
        level: 9,
        overtaking: 49,
        defending: 54,
        qualifying: 57,
        raceStart: 62,
        tireManagement: 58,
      },
      {
        level: 10,
        overtaking: 52,
        defending: 57,
        qualifying: 60,
        raceStart: 65,
        tireManagement: 61,
      },
      {
        level: 11,
        overtaking: 56,
        defending: 61,
        qualifying: 64,
        raceStart: 69,
        tireManagement: 65,
      },
    ],
  },
  {
    id: 26,
    name: 'Zhou Guanyu',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        overtaking: 29,
        defending: 32,
        qualifying: 36,
        raceStart: 26,
        tireManagement: 37,
      },
      {
        level: 2,
        overtaking: 34,
        defending: 37,
        qualifying: 41,
        raceStart: 31,
        tireManagement: 42,
      },
      {
        level: 3,
        overtaking: 38,
        defending: 41,
        qualifying: 45,
        raceStart: 35,
        tireManagement: 46,
      },
      {
        level: 4,
        overtaking: 43,
        defending: 46,
        qualifying: 50,
        raceStart: 40,
        tireManagement: 51,
      },
      {
        level: 5,
        overtaking: 48,
        defending: 51,
        qualifying: 55,
        raceStart: 45,
        tireManagement: 56,
      },
      {
        level: 6,
        overtaking: 52,
        defending: 55,
        qualifying: 59,
        raceStart: 49,
        tireManagement: 69,
      },
      {
        level: 7,
        overtaking: 57,
        defending: 60,
        qualifying: 64,
        raceStart: 54,
        tireManagement: 65,
      },
      {
        level: 8,
        overtaking: 61,
        defending: 64,
        qualifying: 68,
        raceStart: 58,
        tireManagement: 69,
      },
      {
        level: 9,
        overtaking: 66,
        defending: 69,
        qualifying: 73,
        raceStart: 63,
        tireManagement: 74,
      },
    ],
  },
  {
    id: 27,
    name: 'Logan Sargeant',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        overtaking: 27,
        defending: 28,
        qualifying: 33,
        raceStart: 35,
        tireManagement: 37,
      },
      {
        level: 2,
        overtaking: 32,
        defending: 33,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 42,
      },
      {
        level: 3,
        overtaking: 36,
        defending: 37,
        qualifying: 42,
        raceStart: 44,
        tireManagement: 46,
      },
      {
        level: 4,
        overtaking: 41,
        defending: 42,
        qualifying: 47,
        raceStart: 49,
        tireManagement: 51,
      },
      {
        level: 5,
        overtaking: 46,
        defending: 47,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 56,
      },
      {
        level: 6,
        overtaking: 50,
        defending: 51,
        qualifying: 56,
        raceStart: 58,
        tireManagement: 60,
      },
      {
        level: 7,
        overtaking: 55,
        defending: 56,
        qualifying: 61,
        raceStart: 63,
        tireManagement: 65,
      },
      {
        level: 8,
        overtaking: 59,
        defending: 60,
        qualifying: 65,
        raceStart: 67,
        tireManagement: 69,
      },
      {
        level: 9,
        overtaking: 64,
        defending: 65,
        qualifying: 70,
        raceStart: 72,
        tireManagement: 74,
      },
    ],
  },
  {
    id: 28,
    name: 'Nico Hulkenberg',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        overtaking: 31,
        defending: 36,
        qualifying: 39,
        raceStart: 26,
        tireManagement: 28,
      },
      {
        level: 2,
        overtaking: 36,
        defending: 41,
        qualifying: 44,
        raceStart: 31,
        tireManagement: 33,
      },
      {
        level: 3,
        overtaking: 40,
        defending: 45,
        qualifying: 48,
        raceStart: 35,
        tireManagement: 37,
      },
      {
        level: 4,
        overtaking: 45,
        defending: 50,
        qualifying: 53,
        raceStart: 40,
        tireManagement: 42,
      },
      {
        level: 5,
        overtaking: 50,
        defending: 55,
        qualifying: 58,
        raceStart: 45,
        tireManagement: 47,
      },
      {
        level: 6,
        overtaking: 54,
        defending: 59,
        qualifying: 62,
        raceStart: 49,
        tireManagement: 51,
      },
      {
        level: 7,
        overtaking: 59,
        defending: 64,
        qualifying: 67,
        raceStart: 54,
        tireManagement: 56,
      },
      {
        level: 8,
        overtaking: 63,
        defending: 68,
        qualifying: 71,
        raceStart: 58,
        tireManagement: 60,
      },
      {
        level: 9,
        overtaking: 68,
        defending: 73,
        qualifying: 76,
        raceStart: 63,
        tireManagement: 65,
      },
    ],
  },
  {
    id: 29,
    name: 'Alex Albon',
    rarity: 'rare',
    series: 6,
    stats: [
      {
        level: 1,
        overtaking: 38,
        defending: 27,
        qualifying: 29,
        raceStart: 31,
        tireManagement: 35,
      },
      {
        level: 2,
        overtaking: 43,
        defending: 32,
        qualifying: 34,
        raceStart: 36,
        tireManagement: 40,
      },
      {
        level: 3,
        overtaking: 47,
        defending: 36,
        qualifying: 38,
        raceStart: 40,
        tireManagement: 44,
      },
      {
        level: 4,
        overtaking: 52,
        defending: 41,
        qualifying: 43,
        raceStart: 45,
        tireManagement: 49,
      },
      {
        level: 5,
        overtaking: 57,
        defending: 46,
        qualifying: 48,
        raceStart: 50,
        tireManagement: 54,
      },
      {
        level: 6,
        overtaking: 62,
        defending: 50,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 58,
      },
      {
        level: 7,
        overtaking: 66,
        defending: 55,
        qualifying: 57,
        raceStart: 59,
        tireManagement: 63,
      },
      {
        level: 8,
        overtaking: 70,
        defending: 59,
        qualifying: 61,
        raceStart: 63,
        tireManagement: 67,
      },
      {
        level: 9,
        overtaking: 75,
        defending: 64,
        qualifying: 66,
        raceStart: 68,
        tireManagement: 72,
      },
    ],
  },
  {
    id: 30,
    name: 'Nico Hulkenberg',
    rarity: 'epic',
    series: 6,
    stats: [
      {
        level: 1,
        overtaking: 32,
        defending: 37,
        qualifying: 40,
        raceStart: 27,
        tireManagement: 29,
      },
      {
        level: 2,
        overtaking: 37,
        defending: 42,
        qualifying: 45,
        raceStart: 32,
        tireManagement: 34,
      },
      {
        level: 3,
        overtaking: 43,
        defending: 48,
        qualifying: 51,
        raceStart: 38,
        tireManagement: 40,
      },
      {
        level: 4,
        overtaking: 48,
        defending: 53,
        qualifying: 56,
        raceStart: 43,
        tireManagement: 45,
      },
      {
        level: 5,
        overtaking: 54,
        defending: 59,
        qualifying: 62,
        raceStart: 49,
        tireManagement: 51,
      },
      {
        level: 6,
        overtaking: 59,
        defending: 64,
        qualifying: 67,
        raceStart: 54,
        tireManagement: 56,
      },
      {
        level: 7,
        overtaking: 65,
        defending: 70,
        qualifying: 73,
        raceStart: 60,
        tireManagement: 62,
      },
      {
        level: 8,
        overtaking: 70,
        defending: 75,
        qualifying: 78,
        raceStart: 65,
        tireManagement: 67,
      },
    ],
  },
  {
    id: 31,
    name: 'Yuki Tsunoda',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        overtaking: 34,
        defending: 37,
        qualifying: 29,
        raceStart: 42,
        tireManagement: 33,
      },
      {
        level: 2,
        overtaking: 39,
        defending: 42,
        qualifying: 34,
        raceStart: 47,
        tireManagement: 38,
      },
      {
        level: 3,
        overtaking: 44,
        defending: 46,
        qualifying: 39,
        raceStart: 52,
        tireManagement: 43,
      },
      {
        level: 4,
        overtaking: 48,
        defending: 51,
        qualifying: 43,
        raceStart: 56,
        tireManagement: 47,
      },
      {
        level: 5,
        overtaking: 53,
        defending: 56,
        qualifying: 48,
        raceStart: 61,
        tireManagement: 52,
      },
      {
        level: 6,
        overtaking: 58,
        defending: 60,
        qualifying: 53,
        raceStart: 66,
        tireManagement: 57,
      },
      {
        level: 7,
        overtaking: 63,
        defending: 65,
        qualifying: 58,
        raceStart: 71,
        tireManagement: 62,
      },
      {
        level: 8,
        overtaking: 67,
        defending: 70,
        qualifying: 62,
        raceStart: 75,
        tireManagement: 66,
      },
      {
        level: 9,
        overtaking: 72,
        defending: 75,
        qualifying: 67,
        raceStart: 80,
        tireManagement: 71,
      },
    ],
  },
  {
    id: 32,
    name: 'Valtteri Bottas',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        overtaking: 42,
        defending: 32,
        qualifying: 35,
        raceStart: 37,
        tireManagement: 29,
      },
      {
        level: 2,
        overtaking: 47,
        defending: 37,
        qualifying: 40,
        raceStart: 42,
        tireManagement: 34,
      },
      {
        level: 3,
        overtaking: 52,
        defending: 42,
        qualifying: 45,
        raceStart: 47,
        tireManagement: 39,
      },
      {
        level: 4,
        overtaking: 56,
        defending: 46,
        qualifying: 49,
        raceStart: 51,
        tireManagement: 43,
      },
      {
        level: 5,
        overtaking: 61,
        defending: 51,
        qualifying: 54,
        raceStart: 56,
        tireManagement: 48,
      },
      {
        level: 6,
        overtaking: 66,
        defending: 56,
        qualifying: 59,
        raceStart: 61,
        tireManagement: 53,
      },
      {
        level: 7,
        overtaking: 71,
        defending: 61,
        qualifying: 64,
        raceStart: 66,
        tireManagement: 58,
      },
      {
        level: 8,
        overtaking: 75,
        defending: 65,
        qualifying: 68,
        raceStart: 70,
        tireManagement: 62,
      },
      {
        level: 9,
        overtaking: 80,
        defending: 70,
        qualifying: 73,
        raceStart: 75,
        tireManagement: 67,
      },
    ],
  },
  {
    id: 33,
    name: 'Kevin Magnussen',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        overtaking: 28,
        defending: 42,
        qualifying: 32,
        raceStart: 36,
        tireManagement: 37,
      },
      {
        level: 2,
        overtaking: 33,
        defending: 47,
        qualifying: 37,
        raceStart: 41,
        tireManagement: 42,
      },
      {
        level: 3,
        overtaking: 38,
        defending: 52,
        qualifying: 42,
        raceStart: 46,
        tireManagement: 47,
      },
      {
        level: 4,
        overtaking: 42,
        defending: 56,
        qualifying: 46,
        raceStart: 50,
        tireManagement: 51,
      },
      {
        level: 5,
        overtaking: 47,
        defending: 61,
        qualifying: 51,
        raceStart: 55,
        tireManagement: 56,
      },
      {
        level: 6,
        overtaking: 52,
        defending: 66,
        qualifying: 56,
        raceStart: 60,
        tireManagement: 61,
      },
      {
        level: 7,
        overtaking: 57,
        defending: 71,
        qualifying: 61,
        raceStart: 65,
        tireManagement: 66,
      },
      {
        level: 8,
        overtaking: 61,
        defending: 75,
        qualifying: 65,
        raceStart: 69,
        tireManagement: 70,
      },
      {
        level: 9,
        overtaking: 66,
        defending: 80,
        qualifying: 70,
        raceStart: 74,
        tireManagement: 75,
      },
    ],
  },
  {
    id: 34,
    name: 'Esteban Ocon',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        overtaking: 39,
        defending: 28,
        qualifying: 40,
        raceStart: 33,
        tireManagement: 35,
      },
      {
        level: 2,
        overtaking: 44,
        defending: 33,
        qualifying: 45,
        raceStart: 38,
        tireManagement: 40,
      },
      {
        level: 3,
        overtaking: 49,
        defending: 38,
        qualifying: 50,
        raceStart: 43,
        tireManagement: 45,
      },
      {
        level: 4,
        overtaking: 53,
        defending: 42,
        qualifying: 54,
        raceStart: 47,
        tireManagement: 49,
      },
      {
        level: 5,
        overtaking: 58,
        defending: 47,
        qualifying: 59,
        raceStart: 52,
        tireManagement: 54,
      },
      {
        level: 6,
        overtaking: 63,
        defending: 52,
        qualifying: 64,
        raceStart: 57,
        tireManagement: 59,
      },
      {
        level: 7,
        overtaking: 68,
        defending: 57,
        qualifying: 69,
        raceStart: 62,
        tireManagement: 64,
      },
      {
        level: 8,
        overtaking: 72,
        defending: 61,
        qualifying: 73,
        raceStart: 66,
        tireManagement: 68,
      },
      {
        level: 9,
        overtaking: 77,
        defending: 66,
        qualifying: 78,
        raceStart: 71,
        tireManagement: 73,
      },
    ],
  },
  {
    id: 35,
    name: 'Pierre Gasly',
    rarity: 'rare',
    series: 7,
    stats: [
      {
        level: 1,
        overtaking: 34,
        defending: 39,
        qualifying: 29,
        raceStart: 31,
        tireManagement: 42,
      },
      {
        level: 2,
        overtaking: 39,
        defending: 44,
        qualifying: 34,
        raceStart: 36,
        tireManagement: 47,
      },
      {
        level: 3,
        overtaking: 44,
        defending: 49,
        qualifying: 39,
        raceStart: 41,
        tireManagement: 52,
      },
      {
        level: 4,
        overtaking: 48,
        defending: 53,
        qualifying: 43,
        raceStart: 45,
        tireManagement: 56,
      },
      {
        level: 5,
        overtaking: 53,
        defending: 58,
        qualifying: 48,
        raceStart: 50,
        tireManagement: 61,
      },
      {
        level: 6,
        overtaking: 58,
        defending: 63,
        qualifying: 53,
        raceStart: 55,
        tireManagement: 66,
      },
      {
        level: 7,
        overtaking: 63,
        defending: 68,
        qualifying: 58,
        raceStart: 60,
        tireManagement: 71,
      },
      {
        level: 8,
        overtaking: 67,
        defending: 72,
        qualifying: 62,
        raceStart: 64,
        tireManagement: 75,
      },
      {
        level: 9,
        overtaking: 72,
        defending: 77,
        qualifying: 67,
        raceStart: 69,
        tireManagement: 80,
      },
    ],
  },
  {
    id: 36,
    name: 'Sergio Perez',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        overtaking: 35,
        defending: 46,
        qualifying: 39,
        raceStart: 41,
        tireManagement: 34,
      },
      {
        level: 2,
        overtaking: 40,
        defending: 51,
        qualifying: 44,
        raceStart: 46,
        tireManagement: 39,
      },
      {
        level: 3,
        overtaking: 44,
        defending: 55,
        qualifying: 48,
        raceStart: 50,
        tireManagement: 43,
      },
      {
        level: 4,
        overtaking: 49,
        defending: 60,
        qualifying: 53,
        raceStart: 55,
        tireManagement: 48,
      },
      {
        level: 5,
        overtaking: 54,
        defending: 65,
        qualifying: 58,
        raceStart: 60,
        tireManagement: 53,
      },
      {
        level: 6,
        overtaking: 58,
        defending: 69,
        qualifying: 62,
        raceStart: 64,
        tireManagement: 57,
      },
      {
        level: 7,
        overtaking: 63,
        defending: 74,
        qualifying: 67,
        raceStart: 69,
        tireManagement: 62,
      },
      {
        level: 8,
        overtaking: 67,
        defending: 78,
        qualifying: 71,
        raceStart: 73,
        tireManagement: 66,
      },
      {
        level: 9,
        overtaking: 72,
        defending: 83,
        qualifying: 76,
        raceStart: 78,
        tireManagement: 71,
      },
    ],
  },
  {
    id: 37,
    name: 'Lance Stroll',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        overtaking: 42,
        defending: 33,
        qualifying: 37,
        raceStart: 44,
        tireManagement: 39,
      },
      {
        level: 2,
        overtaking: 47,
        defending: 38,
        qualifying: 42,
        raceStart: 49,
        tireManagement: 44,
      },
      {
        level: 3,
        overtaking: 51,
        defending: 42,
        qualifying: 46,
        raceStart: 53,
        tireManagement: 48,
      },
      {
        level: 4,
        overtaking: 56,
        defending: 47,
        qualifying: 51,
        raceStart: 58,
        tireManagement: 53,
      },
      {
        level: 5,
        overtaking: 61,
        defending: 52,
        qualifying: 56,
        raceStart: 63,
        tireManagement: 58,
      },
      {
        level: 6,
        overtaking: 65,
        defending: 56,
        qualifying: 60,
        raceStart: 67,
        tireManagement: 62,
      },
      {
        level: 7,
        overtaking: 70,
        defending: 61,
        qualifying: 65,
        raceStart: 72,
        tireManagement: 67,
      },
      {
        level: 8,
        overtaking: 74,
        defending: 65,
        qualifying: 69,
        raceStart: 76,
        tireManagement: 71,
      },
      {
        level: 9,
        overtaking: 79,
        defending: 70,
        qualifying: 74,
        raceStart: 81,
        tireManagement: 76,
      },
    ],
  },
  {
    id: 38,
    name: 'George Russell',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        overtaking: 45,
        defending: 40,
        qualifying: 41,
        raceStart: 33,
        tireManagement: 36,
      },
      {
        level: 2,
        overtaking: 50,
        defending: 45,
        qualifying: 46,
        raceStart: 38,
        tireManagement: 41,
      },
      {
        level: 3,
        overtaking: 54,
        defending: 49,
        qualifying: 50,
        raceStart: 42,
        tireManagement: 45,
      },
      {
        level: 4,
        overtaking: 59,
        defending: 54,
        qualifying: 55,
        raceStart: 47,
        tireManagement: 50,
      },
      {
        level: 5,
        overtaking: 64,
        defending: 59,
        qualifying: 60,
        raceStart: 52,
        tireManagement: 55,
      },
      {
        level: 6,
        overtaking: 68,
        defending: 63,
        qualifying: 64,
        raceStart: 56,
        tireManagement: 59,
      },
      {
        level: 7,
        overtaking: 73,
        defending: 68,
        qualifying: 69,
        raceStart: 61,
        tireManagement: 64,
      },
      {
        level: 8,
        overtaking: 77,
        defending: 72,
        qualifying: 73,
        raceStart: 65,
        tireManagement: 68,
      },
      {
        level: 9,
        overtaking: 82,
        defending: 77,
        qualifying: 78,
        raceStart: 70,
        tireManagement: 73,
      },
    ],
  },
  {
    id: 39,
    name: 'Carlos Sainz',
    rarity: 'rare',
    series: 8,
    stats: [
      {
        level: 1,
        overtaking: 34,
        defending: 35,
        qualifying: 45,
        raceStart: 40,
        tireManagement: 41,
      },
      {
        level: 2,
        overtaking: 39,
        defending: 40,
        qualifying: 50,
        raceStart: 45,
        tireManagement: 46,
      },
      {
        level: 3,
        overtaking: 43,
        defending: 44,
        qualifying: 54,
        raceStart: 49,
        tireManagement: 50,
      },
      {
        level: 4,
        overtaking: 48,
        defending: 49,
        qualifying: 59,
        raceStart: 54,
        tireManagement: 55,
      },
      {
        level: 5,
        overtaking: 53,
        defending: 54,
        qualifying: 64,
        raceStart: 59,
        tireManagement: 60,
      },
      {
        level: 6,
        overtaking: 57,
        defending: 58,
        qualifying: 68,
        raceStart: 63,
        tireManagement: 64,
      },
      {
        level: 7,
        overtaking: 62,
        defending: 63,
        qualifying: 73,
        raceStart: 68,
        tireManagement: 69,
      },
      {
        level: 8,
        overtaking: 66,
        defending: 67,
        qualifying: 77,
        raceStart: 72,
        tireManagement: 73,
      },
      {
        level: 9,
        overtaking: 71,
        defending: 72,
        qualifying: 82,
        raceStart: 77,
        tireManagement: 78,
      },
    ],
  },
  {
    id: 40,
    name: 'Nyck De Vries',
    rarity: 'epic',
    series: 8,
    stats: [
      {
        level: 1,
        overtaking: 45,
        defending: 47,
        qualifying: 34,
        raceStart: 39,
        tireManagement: 40,
      },
      {
        level: 2,
        overtaking: 50,
        defending: 52,
        qualifying: 39,
        raceStart: 44,
        tireManagement: 45,
      },
      {
        level: 3,
        overtaking: 56,
        defending: 58,
        qualifying: 45,
        raceStart: 50,
        tireManagement: 51,
      },
      {
        level: 4,
        overtaking: 61,
        defending: 63,
        qualifying: 50,
        raceStart: 55,
        tireManagement: 56,
      },
      {
        level: 5,
        overtaking: 66,
        defending: 68,
        qualifying: 55,
        raceStart: 60,
        tireManagement: 61,
      },
      {
        level: 6,
        overtaking: 71,
        defending: 73,
        qualifying: 60,
        raceStart: 65,
        tireManagement: 66,
      },
      {
        level: 7,
        overtaking: 77,
        defending: 79,
        qualifying: 66,
        raceStart: 71,
        tireManagement: 72,
      },
      {
        level: 8,
        overtaking: 82,
        defending: 84,
        qualifying: 71,
        raceStart: 76,
        tireManagement: 77,
      },
    ],
  },
  {
    id: 41,
    name: 'Fernando Alonso',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        overtaking: 49,
        defending: 42,
        qualifying: 39,
        raceStart: 47,
        tireManagement: 38,
      },
      {
        level: 2,
        overtaking: 54,
        defending: 47,
        qualifying: 44,
        raceStart: 52,
        tireManagement: 43,
      },
      {
        level: 3,
        overtaking: 58,
        defending: 51,
        qualifying: 48,
        raceStart: 56,
        tireManagement: 47,
      },
      {
        level: 4,
        overtaking: 63,
        defending: 56,
        qualifying: 53,
        raceStart: 61,
        tireManagement: 52,
      },
      {
        level: 5,
        overtaking: 68,
        defending: 61,
        qualifying: 58,
        raceStart: 66,
        tireManagement: 57,
      },
      {
        level: 6,
        overtaking: 72,
        defending: 65,
        qualifying: 62,
        raceStart: 70,
        tireManagement: 61,
      },
      {
        level: 7,
        overtaking: 77,
        defending: 70,
        qualifying: 67,
        raceStart: 75,
        tireManagement: 66,
      },
      {
        level: 8,
        overtaking: 81,
        defending: 74,
        qualifying: 71,
        raceStart: 79,
        tireManagement: 70,
      },
      {
        level: 9,
        overtaking: 86,
        defending: 79,
        qualifying: 76,
        raceStart: 84,
        tireManagement: 75,
      },
    ],
  },
  {
    id: 42,
    name: 'Lando Norris',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        overtaking: 47,
        defending: 36,
        qualifying: 41,
        raceStart: 42,
        tireManagement: 49,
      },
      {
        level: 2,
        overtaking: 52,
        defending: 41,
        qualifying: 46,
        raceStart: 47,
        tireManagement: 54,
      },
      {
        level: 3,
        overtaking: 56,
        defending: 45,
        qualifying: 50,
        raceStart: 51,
        tireManagement: 58,
      },
      {
        level: 4,
        overtaking: 61,
        defending: 50,
        qualifying: 55,
        raceStart: 56,
        tireManagement: 63,
      },
      {
        level: 5,
        overtaking: 66,
        defending: 55,
        qualifying: 60,
        raceStart: 61,
        tireManagement: 68,
      },
      {
        level: 6,
        overtaking: 70,
        defending: 59,
        qualifying: 64,
        raceStart: 65,
        tireManagement: 72,
      },
      {
        level: 7,
        overtaking: 75,
        defending: 64,
        qualifying: 69,
        raceStart: 70,
        tireManagement: 77,
      },
      {
        level: 8,
        overtaking: 79,
        defending: 68,
        qualifying: 73,
        raceStart: 74,
        tireManagement: 81,
      },
      {
        level: 9,
        overtaking: 84,
        defending: 73,
        qualifying: 78,
        raceStart: 79,
        tireManagement: 86,
      },
    ],
  },
  {
    id: 43,
    name: 'Lewis Hamilton',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        overtaking: 36,
        defending: 41,
        qualifying: 44,
        raceStart: 49,
        tireManagement: 45,
      },
      {
        level: 2,
        overtaking: 41,
        defending: 46,
        qualifying: 49,
        raceStart: 54,
        tireManagement: 50,
      },
      {
        level: 3,
        overtaking: 45,
        defending: 50,
        qualifying: 53,
        raceStart: 58,
        tireManagement: 54,
      },
      {
        level: 4,
        overtaking: 50,
        defending: 55,
        qualifying: 58,
        raceStart: 63,
        tireManagement: 59,
      },
      {
        level: 5,
        overtaking: 55,
        defending: 60,
        qualifying: 63,
        raceStart: 68,
        tireManagement: 64,
      },
      {
        level: 6,
        overtaking: 59,
        defending: 64,
        qualifying: 67,
        raceStart: 72,
        tireManagement: 68,
      },
      {
        level: 7,
        overtaking: 64,
        defending: 69,
        qualifying: 72,
        raceStart: 77,
        tireManagement: 73,
      },
      {
        level: 8,
        overtaking: 68,
        defending: 73,
        qualifying: 76,
        raceStart: 81,
        tireManagement: 77,
      },
      {
        level: 9,
        overtaking: 73,
        defending: 78,
        qualifying: 81,
        raceStart: 86,
        tireManagement: 82,
      },
    ],
  },
  {
    id: 44,
    name: 'Charles Leclerc',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        overtaking: 43,
        defending: 49,
        qualifying: 47,
        raceStart: 37,
        tireManagement: 39,
      },
      {
        level: 2,
        overtaking: 48,
        defending: 54,
        qualifying: 52,
        raceStart: 42,
        tireManagement: 44,
      },
      {
        level: 3,
        overtaking: 52,
        defending: 58,
        qualifying: 56,
        raceStart: 46,
        tireManagement: 48,
      },
      {
        level: 4,
        overtaking: 57,
        defending: 63,
        qualifying: 61,
        raceStart: 51,
        tireManagement: 53,
      },
      {
        level: 5,
        overtaking: 62,
        defending: 68,
        qualifying: 66,
        raceStart: 56,
        tireManagement: 58,
      },
      {
        level: 6,
        overtaking: 66,
        defending: 72,
        qualifying: 70,
        raceStart: 60,
        tireManagement: 62,
      },
      {
        level: 7,
        overtaking: 71,
        defending: 77,
        qualifying: 75,
        raceStart: 65,
        tireManagement: 67,
      },
      {
        level: 8,
        overtaking: 75,
        defending: 81,
        qualifying: 79,
        raceStart: 69,
        tireManagement: 71,
      },
      {
        level: 9,
        overtaking: 80,
        defending: 86,
        qualifying: 84,
        raceStart: 74,
        tireManagement: 76,
      },
    ],
  },
  {
    id: 45,
    name: 'Max Verstappen',
    rarity: 'rare',
    series: 9,
    stats: [
      {
        level: 1,
        overtaking: 47,
        defending: 36,
        qualifying: 49,
        raceStart: 39,
        tireManagement: 44,
      },
      {
        level: 2,
        overtaking: 52,
        defending: 41,
        qualifying: 54,
        raceStart: 44,
        tireManagement: 49,
      },
      {
        level: 3,
        overtaking: 56,
        defending: 45,
        qualifying: 58,
        raceStart: 48,
        tireManagement: 53,
      },
      {
        level: 4,
        overtaking: 61,
        defending: 50,
        qualifying: 63,
        raceStart: 53,
        tireManagement: 58,
      },
      {
        level: 5,
        overtaking: 66,
        defending: 55,
        qualifying: 68,
        raceStart: 58,
        tireManagement: 63,
      },
      {
        level: 6,
        overtaking: 70,
        defending: 59,
        qualifying: 72,
        raceStart: 62,
        tireManagement: 67,
      },
      {
        level: 7,
        overtaking: 75,
        defending: 64,
        qualifying: 77,
        raceStart: 67,
        tireManagement: 72,
      },
      {
        level: 8,
        overtaking: 79,
        defending: 68,
        qualifying: 81,
        raceStart: 71,
        tireManagement: 76,
      },
      {
        level: 9,
        overtaking: 84,
        defending: 73,
        qualifying: 86,
        raceStart: 76,
        tireManagement: 81,
      },
    ],
  },
  {
    id: 46,
    name: 'Zhou Guanyu',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        overtaking: 45,
        defending: 48,
        qualifying: 52,
        raceStart: 42,
        tireManagement: 53,
      },
      {
        level: 2,
        overtaking: 50,
        defending: 53,
        qualifying: 57,
        raceStart: 47,
        tireManagement: 58,
      },
      {
        level: 3,
        overtaking: 56,
        defending: 59,
        qualifying: 63,
        raceStart: 53,
        tireManagement: 64,
      },
      {
        level: 4,
        overtaking: 61,
        defending: 64,
        qualifying: 68,
        raceStart: 58,
        tireManagement: 69,
      },
      {
        level: 5,
        overtaking: 67,
        defending: 70,
        qualifying: 74,
        raceStart: 64,
        tireManagement: 75,
      },
      {
        level: 6,
        overtaking: 72,
        defending: 75,
        qualifying: 79,
        raceStart: 69,
        tireManagement: 80,
      },
      {
        level: 7,
        overtaking: 78,
        defending: 81,
        qualifying: 85,
        raceStart: 75,
        tireManagement: 86,
      },
      {
        level: 8,
        overtaking: 83,
        defending: 86,
        qualifying: 90,
        raceStart: 80,
        tireManagement: 91,
      },
    ],
  },
  {
    id: 47,
    name: 'Yuki Tsunoda',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        overtaking: 47,
        defending: 50,
        qualifying: 42,
        raceStart: 55,
        tireManagement: 46,
      },
      {
        level: 2,
        overtaking: 52,
        defending: 55,
        qualifying: 47,
        raceStart: 60,
        tireManagement: 51,
      },
      {
        level: 3,
        overtaking: 58,
        defending: 61,
        qualifying: 53,
        raceStart: 66,
        tireManagement: 57,
      },
      {
        level: 4,
        overtaking: 63,
        defending: 66,
        qualifying: 58,
        raceStart: 71,
        tireManagement: 62,
      },
      {
        level: 5,
        overtaking: 69,
        defending: 72,
        qualifying: 64,
        raceStart: 77,
        tireManagement: 68,
      },
      {
        level: 6,
        overtaking: 74,
        defending: 77,
        qualifying: 69,
        raceStart: 82,
        tireManagement: 73,
      },
      {
        level: 7,
        overtaking: 80,
        defending: 83,
        qualifying: 75,
        raceStart: 88,
        tireManagement: 79,
      },
      {
        level: 8,
        overtaking: 85,
        defending: 88,
        qualifying: 80,
        raceStart: 93,
        tireManagement: 84,
      },
    ],
  },
  {
    id: 48,
    name: 'Esteban Ocon',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        overtaking: 52,
        defending: 41,
        qualifying: 53,
        raceStart: 46,
        tireManagement: 48,
      },
      {
        level: 2,
        overtaking: 57,
        defending: 46,
        qualifying: 58,
        raceStart: 51,
        tireManagement: 53,
      },
      {
        level: 3,
        overtaking: 63,
        defending: 52,
        qualifying: 64,
        raceStart: 57,
        tireManagement: 59,
      },
      {
        level: 4,
        overtaking: 68,
        defending: 57,
        qualifying: 69,
        raceStart: 62,
        tireManagement: 64,
      },
      {
        level: 5,
        overtaking: 74,
        defending: 63,
        qualifying: 75,
        raceStart: 68,
        tireManagement: 70,
      },
      {
        level: 6,
        overtaking: 79,
        defending: 68,
        qualifying: 80,
        raceStart: 73,
        tireManagement: 75,
      },
      {
        level: 7,
        overtaking: 85,
        defending: 74,
        qualifying: 86,
        raceStart: 79,
        tireManagement: 81,
      },
      {
        level: 8,
        overtaking: 90,
        defending: 79,
        qualifying: 91,
        raceStart: 84,
        tireManagement: 86,
      },
    ],
  },
  {
    id: 49,
    name: 'Valtteri Bottas',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        overtaking: 55,
        defending: 45,
        qualifying: 48,
        raceStart: 50,
        tireManagement: 42,
      },
      {
        level: 2,
        overtaking: 60,
        defending: 50,
        qualifying: 53,
        raceStart: 55,
        tireManagement: 47,
      },
      {
        level: 3,
        overtaking: 66,
        defending: 56,
        qualifying: 59,
        raceStart: 61,
        tireManagement: 53,
      },
      {
        level: 4,
        overtaking: 71,
        defending: 61,
        qualifying: 64,
        raceStart: 66,
        tireManagement: 58,
      },
      {
        level: 5,
        overtaking: 77,
        defending: 67,
        qualifying: 70,
        raceStart: 72,
        tireManagement: 64,
      },
      {
        level: 6,
        overtaking: 82,
        defending: 72,
        qualifying: 75,
        raceStart: 77,
        tireManagement: 69,
      },
      {
        level: 7,
        overtaking: 88,
        defending: 78,
        qualifying: 81,
        raceStart: 83,
        tireManagement: 75,
      },
      {
        level: 8,
        overtaking: 93,
        defending: 83,
        qualifying: 86,
        raceStart: 88,
        tireManagement: 80,
      },
    ],
  },
  {
    id: 50,
    name: 'Kevin Magnussen',
    rarity: 'epic',
    series: 10,
    stats: [
      {
        level: 1,
        overtaking: 41,
        defending: 55,
        qualifying: 45,
        raceStart: 49,
        tireManagement: 50,
      },
      {
        level: 2,
        overtaking: 46,
        defending: 60,
        qualifying: 50,
        raceStart: 54,
        tireManagement: 55,
      },
      {
        level: 3,
        overtaking: 52,
        defending: 66,
        qualifying: 56,
        raceStart: 60,
        tireManagement: 61,
      },
      {
        level: 4,
        overtaking: 57,
        defending: 71,
        qualifying: 61,
        raceStart: 65,
        tireManagement: 66,
      },
      {
        level: 5,
        overtaking: 63,
        defending: 77,
        qualifying: 67,
        raceStart: 71,
        tireManagement: 72,
      },
      {
        level: 6,
        overtaking: 68,
        defending: 82,
        qualifying: 72,
        raceStart: 76,
        tireManagement: 77,
      },
      {
        level: 7,
        overtaking: 74,
        defending: 88,
        qualifying: 78,
        raceStart: 82,
        tireManagement: 83,
      },
      {
        level: 8,
        overtaking: 79,
        defending: 93,
        qualifying: 83,
        raceStart: 87,
        tireManagement: 88,
      },
    ],
  },
  {
    id: 51,
    name: 'Sergio Perez',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        overtaking: 48,
        defending: 59,
        qualifying: 52,
        raceStart: 54,
        tireManagement: 47,
      },
      {
        level: 2,
        overtaking: 53,
        defending: 64,
        qualifying: 57,
        raceStart: 59,
        tireManagement: 52,
      },
      {
        level: 3,
        overtaking: 59,
        defending: 70,
        qualifying: 63,
        raceStart: 65,
        tireManagement: 58,
      },
      {
        level: 4,
        overtaking: 64,
        defending: 75,
        qualifying: 68,
        raceStart: 70,
        tireManagement: 63,
      },
      {
        level: 5,
        overtaking: 69,
        defending: 80,
        qualifying: 73,
        raceStart: 75,
        tireManagement: 68,
      },
      {
        level: 6,
        overtaking: 74,
        defending: 85,
        qualifying: 78,
        raceStart: 80,
        tireManagement: 73,
      },
      {
        level: 7,
        overtaking: 80,
        defending: 91,
        qualifying: 84,
        raceStart: 86,
        tireManagement: 79,
      },
      {
        level: 8,
        overtaking: 85,
        defending: 96,
        qualifying: 89,
        raceStart: 91,
        tireManagement: 84,
      },
    ],
  },
  {
    id: 52,
    name: 'Pierre Gasly',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        overtaking: 51,
        defending: 56,
        qualifying: 46,
        raceStart: 48,
        tireManagement: 59,
      },
      {
        level: 2,
        overtaking: 56,
        defending: 61,
        qualifying: 51,
        raceStart: 53,
        tireManagement: 64,
      },
      {
        level: 3,
        overtaking: 62,
        defending: 67,
        qualifying: 57,
        raceStart: 59,
        tireManagement: 70,
      },
      {
        level: 4,
        overtaking: 67,
        defending: 72,
        qualifying: 62,
        raceStart: 64,
        tireManagement: 75,
      },
      {
        level: 5,
        overtaking: 72,
        defending: 77,
        qualifying: 67,
        raceStart: 69,
        tireManagement: 80,
      },
      {
        level: 6,
        overtaking: 77,
        defending: 82,
        qualifying: 72,
        raceStart: 74,
        tireManagement: 85,
      },
      {
        level: 7,
        overtaking: 83,
        defending: 88,
        qualifying: 78,
        raceStart: 80,
        tireManagement: 91,
      },
      {
        level: 8,
        overtaking: 88,
        defending: 93,
        qualifying: 83,
        raceStart: 85,
        tireManagement: 96,
      },
    ],
  },
  {
    id: 53,
    name: 'George Russell',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        overtaking: 58,
        defending: 53,
        qualifying: 54,
        raceStart: 46,
        tireManagement: 49,
      },
      {
        level: 2,
        overtaking: 63,
        defending: 58,
        qualifying: 59,
        raceStart: 51,
        tireManagement: 54,
      },
      {
        level: 3,
        overtaking: 69,
        defending: 64,
        qualifying: 65,
        raceStart: 57,
        tireManagement: 60,
      },
      {
        level: 4,
        overtaking: 74,
        defending: 69,
        qualifying: 70,
        raceStart: 62,
        tireManagement: 65,
      },
      {
        level: 5,
        overtaking: 79,
        defending: 74,
        qualifying: 75,
        raceStart: 67,
        tireManagement: 70,
      },
      {
        level: 6,
        overtaking: 84,
        defending: 79,
        qualifying: 80,
        raceStart: 72,
        tireManagement: 75,
      },
      {
        level: 7,
        overtaking: 90,
        defending: 85,
        qualifying: 86,
        raceStart: 78,
        tireManagement: 81,
      },
      {
        level: 8,
        overtaking: 95,
        defending: 90,
        qualifying: 91,
        raceStart: 83,
        tireManagement: 86,
      },
    ],
  },
  {
    id: 54,
    name: 'Lance Stroll',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        overtaking: 55,
        defending: 46,
        qualifying: 50,
        raceStart: 57,
        tireManagement: 52,
      },
      {
        level: 2,
        overtaking: 60,
        defending: 51,
        qualifying: 55,
        raceStart: 62,
        tireManagement: 57,
      },
      {
        level: 3,
        overtaking: 66,
        defending: 57,
        qualifying: 61,
        raceStart: 68,
        tireManagement: 63,
      },
      {
        level: 4,
        overtaking: 71,
        defending: 62,
        qualifying: 66,
        raceStart: 73,
        tireManagement: 68,
      },
      {
        level: 5,
        overtaking: 76,
        defending: 67,
        qualifying: 71,
        raceStart: 78,
        tireManagement: 73,
      },
      {
        level: 6,
        overtaking: 81,
        defending: 72,
        qualifying: 76,
        raceStart: 83,
        tireManagement: 78,
      },
      {
        level: 7,
        overtaking: 87,
        defending: 78,
        qualifying: 82,
        raceStart: 89,
        tireManagement: 84,
      },
      {
        level: 8,
        overtaking: 92,
        defending: 83,
        qualifying: 87,
        raceStart: 94,
        tireManagement: 89,
      },
    ],
  },
  {
    id: 55,
    name: 'Carlos Sainz',
    rarity: 'epic',
    series: 11,
    stats: [
      {
        level: 1,
        overtaking: 47,
        defending: 48,
        qualifying: 58,
        raceStart: 53,
        tireManagement: 54,
      },
      {
        level: 2,
        overtaking: 52,
        defending: 53,
        qualifying: 63,
        raceStart: 58,
        tireManagement: 59,
      },
      {
        level: 3,
        overtaking: 58,
        defending: 59,
        qualifying: 69,
        raceStart: 64,
        tireManagement: 65,
      },
      {
        level: 4,
        overtaking: 63,
        defending: 64,
        qualifying: 74,
        raceStart: 69,
        tireManagement: 70,
      },
      {
        level: 5,
        overtaking: 68,
        defending: 69,
        qualifying: 79,
        raceStart: 74,
        tireManagement: 75,
      },
      {
        level: 6,
        overtaking: 73,
        defending: 74,
        qualifying: 84,
        raceStart: 79,
        tireManagement: 80,
      },
      {
        level: 7,
        overtaking: 79,
        defending: 80,
        qualifying: 90,
        raceStart: 85,
        tireManagement: 86,
      },
      {
        level: 8,
        overtaking: 84,
        defending: 85,
        qualifying: 95,
        raceStart: 90,
        tireManagement: 91,
      },
    ],
  },
  {
    id: 56,
    name: 'Lando Norris',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        overtaking: 60,
        defending: 49,
        qualifying: 54,
        raceStart: 55,
        tireManagement: 62,
      },
      {
        level: 2,
        overtaking: 65,
        defending: 54,
        qualifying: 59,
        raceStart: 60,
        tireManagement: 67,
      },
      {
        level: 3,
        overtaking: 71,
        defending: 60,
        qualifying: 65,
        raceStart: 66,
        tireManagement: 73,
      },
      {
        level: 4,
        overtaking: 76,
        defending: 65,
        qualifying: 70,
        raceStart: 71,
        tireManagement: 78,
      },
      {
        level: 5,
        overtaking: 81,
        defending: 70,
        qualifying: 75,
        raceStart: 76,
        tireManagement: 83,
      },
      {
        level: 6,
        overtaking: 86,
        defending: 75,
        qualifying: 80,
        raceStart: 81,
        tireManagement: 88,
      },
      {
        level: 7,
        overtaking: 92,
        defending: 81,
        qualifying: 86,
        raceStart: 87,
        tireManagement: 94,
      },
      {
        level: 8,
        overtaking: 97,
        defending: 86,
        qualifying: 91,
        raceStart: 92,
        tireManagement: 99,
      },
    ],
  },
  {
    id: 57,
    name: 'Lewis Hamilton',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        overtaking: 49,
        defending: 54,
        qualifying: 57,
        raceStart: 62,
        tireManagement: 58,
      },
      {
        level: 2,
        overtaking: 54,
        defending: 59,
        qualifying: 62,
        raceStart: 67,
        tireManagement: 63,
      },
      {
        level: 3,
        overtaking: 60,
        defending: 65,
        qualifying: 68,
        raceStart: 73,
        tireManagement: 69,
      },
      {
        level: 4,
        overtaking: 65,
        defending: 70,
        qualifying: 73,
        raceStart: 78,
        tireManagement: 74,
      },
      {
        level: 5,
        overtaking: 70,
        defending: 75,
        qualifying: 78,
        raceStart: 83,
        tireManagement: 79,
      },
      {
        level: 6,
        overtaking: 75,
        defending: 80,
        qualifying: 83,
        raceStart: 88,
        tireManagement: 84,
      },
      {
        level: 7,
        overtaking: 81,
        defending: 86,
        qualifying: 89,
        raceStart: 94,
        tireManagement: 90,
      },
      {
        level: 8,
        overtaking: 86,
        defending: 91,
        qualifying: 94,
        raceStart: 99,
        tireManagement: 95,
      },
    ],
  },
  {
    id: 58,
    name: 'Fernando Alonso',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        overtaking: 62,
        defending: 55,
        qualifying: 52,
        raceStart: 60,
        tireManagement: 51,
      },
      {
        level: 2,
        overtaking: 67,
        defending: 60,
        qualifying: 57,
        raceStart: 65,
        tireManagement: 56,
      },
      {
        level: 3,
        overtaking: 73,
        defending: 66,
        qualifying: 63,
        raceStart: 71,
        tireManagement: 62,
      },
      {
        level: 4,
        overtaking: 78,
        defending: 71,
        qualifying: 68,
        raceStart: 76,
        tireManagement: 67,
      },
      {
        level: 5,
        overtaking: 83,
        defending: 76,
        qualifying: 73,
        raceStart: 81,
        tireManagement: 72,
      },
      {
        level: 6,
        overtaking: 88,
        defending: 81,
        qualifying: 78,
        raceStart: 86,
        tireManagement: 77,
      },
      {
        level: 7,
        overtaking: 94,
        defending: 87,
        qualifying: 84,
        raceStart: 92,
        tireManagement: 83,
      },
      {
        level: 8,
        overtaking: 99,
        defending: 92,
        qualifying: 89,
        raceStart: 97,
        tireManagement: 88,
      },
    ],
  },
  {
    id: 59,
    name: 'Charles Leclerc',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        overtaking: 56,
        defending: 62,
        qualifying: 60,
        raceStart: 50,
        tireManagement: 52,
      },
      {
        level: 2,
        overtaking: 61,
        defending: 67,
        qualifying: 65,
        raceStart: 55,
        tireManagement: 57,
      },
      {
        level: 3,
        overtaking: 67,
        defending: 73,
        qualifying: 71,
        raceStart: 61,
        tireManagement: 63,
      },
      {
        level: 4,
        overtaking: 72,
        defending: 78,
        qualifying: 76,
        raceStart: 66,
        tireManagement: 68,
      },
      {
        level: 5,
        overtaking: 77,
        defending: 83,
        qualifying: 81,
        raceStart: 71,
        tireManagement: 73,
      },
      {
        level: 6,
        overtaking: 82,
        defending: 88,
        qualifying: 86,
        raceStart: 76,
        tireManagement: 78,
      },
      {
        level: 7,
        overtaking: 88,
        defending: 94,
        qualifying: 92,
        raceStart: 82,
        tireManagement: 84,
      },
      {
        level: 8,
        overtaking: 93,
        defending: 99,
        qualifying: 97,
        raceStart: 87,
        tireManagement: 89,
      },
    ],
  },
  {
    id: 60,
    name: 'Max Verstappen',
    rarity: 'epic',
    series: 12,
    stats: [
      {
        level: 1,
        overtaking: 60,
        defending: 49,
        qualifying: 62,
        raceStart: 52,
        tireManagement: 57,
      },
      {
        level: 2,
        overtaking: 65,
        defending: 54,
        qualifying: 67,
        raceStart: 57,
        tireManagement: 62,
      },
      {
        level: 3,
        overtaking: 71,
        defending: 60,
        qualifying: 73,
        raceStart: 63,
        tireManagement: 68,
      },
      {
        level: 4,
        overtaking: 76,
        defending: 65,
        qualifying: 78,
        raceStart: 68,
        tireManagement: 73,
      },
      {
        level: 5,
        overtaking: 81,
        defending: 70,
        qualifying: 83,
        raceStart: 73,
        tireManagement: 78,
      },
      {
        level: 6,
        overtaking: 86,
        defending: 75,
        qualifying: 88,
        raceStart: 78,
        tireManagement: 83,
      },
      {
        level: 7,
        overtaking: 92,
        defending: 81,
        qualifying: 94,
        raceStart: 84,
        tireManagement: 89,
      },
      {
        level: 8,
        overtaking: 97,
        defending: 86,
        qualifying: 99,
        raceStart: 89,
        tireManagement: 94,
      },
    ],
  },
] as Driver[];

const createDrivers = () => {
  const driversToSave = prepareDriversData(DRIVERS);

  console.log('Creating drivers file >>');
  createFile('src/features/drivers/constants/drivers.json', driversToSave);
};

export default createDrivers;
